{
  "count": 0,
  "page": 1,
  "pagesize": 50,
  "result": [
    {
      "registry": "Host Images",
      "image_repository_name": "gcr.io/google-containers/hyperkube",
      "image_name": "gcr.io/google-containers/hyperkube:v1.16.6",
      "image_digest": "sha256:ae6fea104d3daa8321f9ba27767b3f8f25eefc37d6cbfea7a611da15cacae153",
      "referenced_vulnerabilities": null,
      "resource": {
        "type": "file",
        "format": "",
        "path": "/usr/lib/python2.7/dist-packages/requests/sessions.py",
        "name": "",
        "version": "",
        "arch": "",
        "cpe": "file:/ff1b7c192fb74a538bf44cae36b264e362fda584",
        "licenses": null,
        "hash": "sha1:ff1b7c192fb74a538bf44cae36b264e362fda584"
      },
      "name": "CVE-2018-18074",
      "description": "The Requests package before 2.20.0 for Python sends an HTTP Authorization header to an http URI upon receiving a same-hostname https-to-http redirect, which makes it easier for remote attackers to discover credentials by sniffing the network.",
      "publish_date": "2018-10-09",
      "modification_date": "2019-10-03",
      "vendor_severity": "high",
      "vendor_cvss2_score": 9.8,
      "vendor_cvss2_vectors": "",
      "vendor_statement": "",
      "vendor_url": "https://github.com/requests/requests/commit/c45d7c49ea75133e52ab22a8e9e13173938e36ff",
      "nvd_severity": "medium",
      "nvd_cvss2_score": 5,
      "nvd_cvss2_vectors": "AV:N/AC:L/Au:N/C:P/I:N/A:N",
      "nvd_cvss3_severity": "critical",
      "nvd_cvss3_score": 9.8,
      "nvd_cvss3_vectors": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
      "nvd_url": "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2018-18074",
      "fix_version": "2.20.0",
      "solution": "2.20.0",
      "classification": "",
      "qualys_ids": null,
      "aqua_score": 9.8,
      "aqua_severity": "critical",
      "aqua_vectors": "",
      "aqua_scoring_system": "CVSS V2",
      "first_found_date": "2020-04-29",
      "last_found_date": "2020-04-29",
      "ancestor_pkg": "",
      "sibling_pkg": "",
      "v_patch_applied_by": "",
      "v_patch_applied_on": "",
      "v_patch_reverted_by": "",
      "v_patch_reverted_on": "",
      "v_patch_enforced_by": "",
      "v_patch_enforced_on": "",
      "v_patch_status": "patch_available",
      "acknowledged_date": "1970-01-01T00:00:00Z",
      "ack_scope": "",
      "ack_comment": "",
      "ack_author": "",
      "ack_expiration_days": 0,
      "ack_expiration_configured_at": "1970-01-01T00:00:00Z",
      "ack_expiration_configured_by": "",
      "v_patch_policy_name": "",
      "v_patch_policy_enforce": false,
      "audit_events_count": 0,
      "block_events_count": 0,
      "image_workload_info": null,
      "base_image_vulnerability": false,
      "base_image_name": ""
    },
    {
      "registry": "Host Images",
      "image_repository_name": "gcr.io/google-containers/hyperkube",
      "image_name": "gcr.io/google-containers/hyperkube:v1.16.6",
      "image_digest": "sha256:ae6fea104d3daa8321f9ba27767b3f8f25eefc37d6cbfea7a611da15cacae153",
      "referenced_vulnerabilities": null,
      "resource": {
        "type": "file",
        "format": "",
        "path": "/usr/lib/python2.7/urlparse.py",
        "name": "",
        "version": "",
        "arch": "",
        "cpe": "file:/ce017e2114603d0d0ec64bb9cc286e27bc6eccd0",
        "licenses": null,
        "hash": "sha1:ce017e2114603d0d0ec64bb9cc286e27bc6eccd0"
      },
      "name": "CVE-2019-10160",
      "description": "A security regression of CVE-2019-9636 was discovered in python since commit d537ab0ff9767ef024f26246899728f0116b1ec3 affecting versions 2.7, 3.5, 3.6, 3.7 and from v3.8.0a4 through v3.8.0b1, which still allows an attacker to exploit CVE-2019-9636 by abusing the user and password parts of a URL. When an application parses user-supplied URLs to store cookies, authentication credentials, or other kind of information, it is possible for an attacker to provide specially crafted URLs to make the application locate host-related information (e.g. cookies, authentication data) and send them to a different host than where it should, unlike if the URLs had been correctly parsed. The result of an attack may vary based on the application.",
      "publish_date": "2019-06-07",
      "modification_date": "2019-10-25",
      "vendor_severity": "high",
      "vendor_cvss2_score": 9.8,
      "vendor_cvss2_vectors": "",
      "vendor_statement": "",
      "vendor_url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2019-10160",
      "nvd_severity": "medium",
      "nvd_cvss2_score": 5,
      "nvd_cvss2_vectors": "AV:N/AC:L/Au:N/C:P/I:N/A:N",
      "nvd_cvss3_severity": "critical",
      "nvd_cvss3_score": 9.8,
      "nvd_cvss3_vectors": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
      "nvd_url": "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2019-10160",
      "fix_version": "2.7.17rc1,v3.5.8rc1,v3.6.9rc1,v3.7.4rc1,v3.8.0b1",
      "solution": "v2.7.17rc1,v3.5.8rc1,v3.6.9rc1,v3.7.4rc1,v3.8.0b1",
      "classification": "",
      "qualys_ids": null,
      "aqua_score": 9.8,
      "aqua_severity": "critical",
      "aqua_vectors": "",
      "aqua_scoring_system": "CVSS V2",
      "first_found_date": "2020-04-29",
      "last_found_date": "2020-04-29",
      "ancestor_pkg": "",
      "sibling_pkg": "",
      "v_patch_applied_by": "",
      "v_patch_applied_on": "",
      "v_patch_reverted_by": "",
      "v_patch_reverted_on": "",
      "v_patch_enforced_by": "",
      "v_patch_enforced_on": "",
      "v_patch_status": "patch_available",
      "acknowledged_date": "1970-01-01T00:00:00Z",
      "ack_scope": "",
      "ack_comment": "",
      "ack_author": "",
      "ack_expiration_days": 0,
      "ack_expiration_configured_at": "1970-01-01T00:00:00Z",
      "ack_expiration_configured_by": "",
      "v_patch_policy_name": "",
      "v_patch_policy_enforce": false,
      "audit_events_count": 0,
      "block_events_count": 0,
      "image_workload_info": null,
      "base_image_vulnerability": false,
      "base_image_name": ""
    },
    {
      "registry": "Host Images",
      "image_repository_name": "gcr.io/google-containers/hyperkube",
      "image_name": "gcr.io/google-containers/hyperkube:v1.16.6",
      "image_digest": "sha256:ae6fea104d3daa8321f9ba27767b3f8f25eefc37d6cbfea7a611da15cacae153",
      "referenced_vulnerabilities": null,
      "resource": {
        "type": "file",
        "format": "",
        "path": "/usr/lib/python2.7/urlparse.py",
        "name": "",
        "version": "",
        "arch": "",
        "cpe": "file:/ce017e2114603d0d0ec64bb9cc286e27bc6eccd0",
        "licenses": null,
        "hash": "sha1:ce017e2114603d0d0ec64bb9cc286e27bc6eccd0"
      },
      "name": "CVE-2019-9636",
      "description": "Python 2.7.x through 2.7.16 and 3.x through 3.7.2 is affected by: Improper Handling of Unicode Encoding (with an incorrect netloc) during NFKC normalization. The impact is: Information disclosure (credentials, cookies, etc. that are cached against a given hostname). The components are: urllib.parse.urlsplit, urllib.parse.urlparse. The attack vector is: A specially crafted URL could be incorrectly parsed to locate cookies or authentication data and send that information to a different host than when parsed correctly.",
      "publish_date": "2019-03-08",
      "modification_date": "2019-06-13",
      "vendor_severity": "high",
      "vendor_cvss2_score": 9.8,
      "vendor_cvss2_vectors": "",
      "vendor_statement": "",
      "vendor_url": "http://www.securityfocus.com/bid/107400",
      "nvd_severity": "medium",
      "nvd_cvss2_score": 5,
      "nvd_cvss2_vectors": "AV:N/AC:L/Au:N/C:P/I:N/A:N",
      "nvd_cvss3_severity": "critical",
      "nvd_cvss3_score": 9.8,
      "nvd_cvss3_vectors": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
      "nvd_url": "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2019-9636",
      "fix_version": "2.7.172.7, 3.5.73.5, 3.6.93.6, 3.7.43.7",
      "solution": "All Python 2.7.x users should upgrade to the latest version >= python-2.7.172.7\nAll Python 3.5.x users should upgrade to the latest version >= python-3.5.73.5/3.5m\nAll Python 3.6.x users should upgrade to the latest version >= python-3.6.93.6/3.6m\nAll Python 3.7x users should upgrade to the latest version >= python-3.7.43.7/3.7m\n\n3.7.3",
      "classification": "",
      "qualys_ids": null,
      "aqua_score": 9.8,
      "aqua_severity": "critical",
      "aqua_vectors": "",
      "aqua_scoring_system": "CVSS V2",
      "first_found_date": "2020-04-29",
      "last_found_date": "2020-04-29",
      "ancestor_pkg": "",
      "sibling_pkg": "",
      "v_patch_applied_by": "",
      "v_patch_applied_on": "",
      "v_patch_reverted_by": "",
      "v_patch_reverted_on": "",
      "v_patch_enforced_by": "",
      "v_patch_enforced_on": "",
      "v_patch_status": "patch_available",
      "acknowledged_date": "1970-01-01T00:00:00Z",
      "ack_scope": "",
      "ack_comment": "",
      "ack_author": "",
      "ack_expiration_days": 0,
      "ack_expiration_configured_at": "1970-01-01T00:00:00Z",
      "ack_expiration_configured_by": "",
      "v_patch_policy_name": "",
      "v_patch_policy_enforce": false,
      "audit_events_count": 0,
      "block_events_count": 0,
      "image_workload_info": null,
      "base_image_vulnerability": false,
      "base_image_name": ""
    },
    {
      "registry": "Host Images",
      "image_repository_name": "gcr.io/google-containers/hyperkube",
      "image_name": "gcr.io/google-containers/hyperkube:v1.16.6",
      "image_digest": "sha256:ae6fea104d3daa8321f9ba27767b3f8f25eefc37d6cbfea7a611da15cacae153",
      "referenced_vulnerabilities": [
        {
          "registry": "",
          "image_repository_name": "",
          "referenced_vulnerabilities": null,
          "resource": {
            "type": "",
            "format": "",
            "path": "",
            "name": "",
            "version": "",
            "arch": "",
            "cpe": "",
            "licenses": null,
            "hash": ""
          },
          "name": "CVE-2019-1349",
          "description": "A remote code execution vulnerability exists when Git for Visual Studio improperly sanitizes input, aka 'Git for Visual Studio Remote Code Execution Vulnerability'. This CVE ID is unique from CVE-2019-1350, CVE-2019-1352, CVE-2019-1354, CVE-2019-1387.",
          "publish_date": "2020-01-24",
          "modification_date": "2020-01-28",
          "vendor_severity": "high",
          "vendor_cvss2_score": 9.3,
          "vendor_cvss2_vectors": "AV:N/AC:M/Au:N/C:C/I:C/A:C",
          "vendor_cvss3_severity": "high",
          "vendor_cvss3_score": 8.8,
          "vendor_cvss3_vectors": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
          "vendor_statement": "https://git.kernel.org/pub/scm/git/git.git/commit/?id=0060fd1511b94c918928fa3708f69a3f33895a4a\nhttps://www.openwall.com/lists/oss-security/2019/12/13/1",
          "vendor_url": "https://security-tracker.debian.org/tracker/CVE-2019-1349",
          "nvd_severity": "high",
          "nvd_cvss2_score": 9.3,
          "nvd_cvss2_vectors": "AV:N/AC:M/Au:N/C:C/I:C/A:C",
          "nvd_cvss3_severity": "high",
          "nvd_cvss3_score": 8.8,
          "nvd_cvss3_vectors": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
          "nvd_url": "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2019-1349",
          "fix_version": "",
          "solution": "",
          "classification": "",
          "qualys_ids": null,
          "aqua_score": 9.3,
          "aqua_severity": "critical",
          "aqua_vectors": "AV:N/AC:M/Au:N/C:C/I:C/A:C",
          "aqua_scoring_system": "CVSS V2",
          "first_found_date": "2020-04-29",
          "last_found_date": "2020-04-29",
          "ancestor_pkg": "",
          "sibling_pkg": "",
          "v_patch_applied_by": "",
          "v_patch_applied_on": "",
          "v_patch_reverted_by": "",
          "v_patch_reverted_on": "",
          "v_patch_enforced_by": "",
          "v_patch_enforced_on": "",
          "v_patch_status": "",
          "acknowledged_date": "0001-01-01T00:00:00Z",
          "ack_scope": "",
          "ack_comment": "",
          "ack_author": "",
          "ack_expiration_days": 0,
          "ack_expiration_configured_at": "0001-01-01T00:00:00Z",
          "ack_expiration_configured_by": "",
          "v_patch_policy_name": "",
          "v_patch_policy_enforce": false,
          "audit_events_count": 0,
          "block_events_count": 0,
          "image_workload_info": null,
          "base_image_vulnerability": false,
          "base_image_name": ""
        },
        {
          "registry": "",
          "image_repository_name": "",
          "referenced_vulnerabilities": null,
          "resource": {
            "type": "",
            "format": "",
            "path": "",
            "name": "",
            "version": "",
            "arch": "",
            "cpe": "",
            "licenses": null,
            "hash": ""
          },
          "name": "CVE-2019-1352",
          "description": "A remote code execution vulnerability exists when Git for Visual Studio improperly sanitizes input, aka 'Git for Visual Studio Remote Code Execution Vulnerability'. This CVE ID is unique from CVE-2019-1349, CVE-2019-1350, CVE-2019-1354, CVE-2019-1387.",
          "publish_date": "2020-01-24",
          "modification_date": "2020-01-28",
          "vendor_severity": "high",
          "vendor_cvss2_score": 9.3,
          "vendor_cvss2_vectors": "AV:N/AC:M/Au:N/C:C/I:C/A:C",
          "vendor_cvss3_severity": "high",
          "vendor_cvss3_score": 8.8,
          "vendor_cvss3_vectors": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
          "vendor_statement": "https://git.kernel.org/pub/scm/git/git.git/commit/?id=7c3745fc6185495d5765628b4dfe1bd2c25a2981\nhttps://www.openwall.com/lists/oss-security/2019/12/13/1\nAdditional hardening for .gitmodules (but not part of the CVE):\nhttps://git.kernel.org/pub/scm/git/git.git/commit/?id=91bd46588e6959e6903e275f78b10bd07830d547",
          "vendor_url": "https://security-tracker.debian.org/tracker/CVE-2019-1352",
          "nvd_severity": "high",
          "nvd_cvss2_score": 9.3,
          "nvd_cvss2_vectors": "AV:N/AC:M/Au:N/C:C/I:C/A:C",
          "nvd_cvss3_severity": "high",
          "nvd_cvss3_score": 8.8,
          "nvd_cvss3_vectors": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
          "nvd_url": "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2019-1352",
          "fix_version": "",
          "solution": "",
          "classification": "",
          "qualys_ids": null,
          "aqua_score": 9.3,
          "aqua_severity": "critical",
          "aqua_vectors": "AV:N/AC:M/Au:N/C:C/I:C/A:C",
          "aqua_scoring_system": "CVSS V2",
          "first_found_date": "2020-04-29",
          "last_found_date": "2020-04-29",
          "ancestor_pkg": "",
          "sibling_pkg": "",
          "v_patch_applied_by": "",
          "v_patch_applied_on": "",
          "v_patch_reverted_by": "",
          "v_patch_reverted_on": "",
          "v_patch_enforced_by": "",
          "v_patch_enforced_on": "",
          "v_patch_status": "",
          "acknowledged_date": "0001-01-01T00:00:00Z",
          "ack_scope": "",
          "ack_comment": "",
          "ack_author": "",
          "ack_expiration_days": 0,
          "ack_expiration_configured_at": "0001-01-01T00:00:00Z",
          "ack_expiration_configured_by": "",
          "v_patch_policy_name": "",
          "v_patch_policy_enforce": false,
          "audit_events_count": 0,
          "block_events_count": 0,
          "image_workload_info": null,
          "base_image_vulnerability": false,
          "base_image_name": ""
        },
        {
          "registry": "",
          "image_repository_name": "",
          "referenced_vulnerabilities": null,
          "resource": {
            "type": "",
            "format": "",
            "path": "",
            "name": "",
            "version": "",
            "arch": "",
            "cpe": "",
            "licenses": null,
            "hash": ""
          },
          "name": "CVE-2019-1353",
          "description": "An issue was found in Git before v2.24.1, v2.23.1, v2.22.2, v2.21.1, v2.20.2, v2.19.3, v2.18.2, v2.17.3, v2.16.6, v2.15.4, and v2.14.6. When running Git in the Windows Subsystem for Linux (also known as \"WSL\") while accessing a working directory on a regular Windows drive, none of the NTFS protections were active.",
          "publish_date": "2020-01-24",
          "modification_date": "2020-03-15",
          "vendor_severity": "high",
          "vendor_cvss2_score": 7.5,
          "vendor_cvss2_vectors": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
          "vendor_cvss3_severity": "critical",
          "vendor_cvss3_score": 9.8,
          "vendor_cvss3_vectors": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
          "vendor_statement": "https://git.kernel.org/pub/scm/git/git.git/commit/?id=9102f958ee5254b10c0be72672aa3305bf4f4704\nhttps://www.openwall.com/lists/oss-security/2019/12/13/1",
          "vendor_url": "https://security-tracker.debian.org/tracker/CVE-2019-1353",
          "nvd_severity": "high",
          "nvd_cvss2_score": 7.5,
          "nvd_cvss2_vectors": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
          "nvd_cvss3_severity": "critical",
          "nvd_cvss3_score": 9.8,
          "nvd_cvss3_vectors": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
          "nvd_url": "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2019-1353",
          "fix_version": "",
          "solution": "",
          "classification": "",
          "qualys_ids": null,
          "aqua_score": 7.5,
          "aqua_severity": "high",
          "aqua_vectors": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
          "aqua_scoring_system": "CVSS V2",
          "first_found_date": "2020-04-29",
          "last_found_date": "2020-04-29",
          "ancestor_pkg": "",
          "sibling_pkg": "",
          "v_patch_applied_by": "",
          "v_patch_applied_on": "",
          "v_patch_reverted_by": "",
          "v_patch_reverted_on": "",
          "v_patch_enforced_by": "",
          "v_patch_enforced_on": "",
          "v_patch_status": "",
          "acknowledged_date": "0001-01-01T00:00:00Z",
          "ack_scope": "",
          "ack_comment": "",
          "ack_author": "",
          "ack_expiration_days": 0,
          "ack_expiration_configured_at": "0001-01-01T00:00:00Z",
          "ack_expiration_configured_by": "",
          "v_patch_policy_name": "",
          "v_patch_policy_enforce": false,
          "audit_events_count": 0,
          "block_events_count": 0,
          "image_workload_info": null,
          "base_image_vulnerability": false,
          "base_image_name": ""
        },
        {
          "registry": "",
          "image_repository_name": "",
          "referenced_vulnerabilities": null,
          "resource": {
            "type": "",
            "format": "",
            "path": "",
            "name": "",
            "version": "",
            "arch": "",
            "cpe": "",
            "licenses": null,
            "hash": ""
          },
          "name": "CVE-2019-1387",
          "description": "An issue was found in Git before v2.24.1, v2.23.1, v2.22.2, v2.21.1, v2.20.2, v2.19.3, v2.18.2, v2.17.3, v2.16.6, v2.15.4, and v2.14.6. Recursive clones are currently affected by a vulnerability that is caused by too-lax validation of submodule names, allowing very targeted attacks via remote code execution in recursive clones.",
          "publish_date": "2019-12-18",
          "modification_date": "2020-01-02",
          "vendor_severity": "medium",
          "vendor_cvss2_score": 6.8,
          "vendor_cvss2_vectors": "AV:N/AC:M/Au:N/C:P/I:P/A:P",
          "vendor_cvss3_severity": "high",
          "vendor_cvss3_score": 8.8,
          "vendor_cvss3_vectors": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
          "vendor_statement": "https://git.kernel.org/pub/scm/git/git.git/commit/?id=a8dee3ca610f5a1d403634492136c887f83b59d2\nhttps://www.openwall.com/lists/oss-security/2019/12/13/1",
          "vendor_url": "https://security-tracker.debian.org/tracker/CVE-2019-1387",
          "nvd_severity": "medium",
          "nvd_cvss2_score": 6.8,
          "nvd_cvss2_vectors": "AV:N/AC:M/Au:N/C:P/I:P/A:P",
          "nvd_cvss3_severity": "high",
          "nvd_cvss3_score": 8.8,
          "nvd_cvss3_vectors": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
          "nvd_url": "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2019-1387",
          "fix_version": "",
          "solution": "",
          "classification": "",
          "qualys_ids": null,
          "aqua_score": 6.8,
          "aqua_severity": "medium",
          "aqua_vectors": "AV:N/AC:M/Au:N/C:P/I:P/A:P",
          "aqua_scoring_system": "CVSS V2",
          "first_found_date": "2020-04-29",
          "last_found_date": "2020-04-29",
          "ancestor_pkg": "",
          "sibling_pkg": "",
          "v_patch_applied_by": "",
          "v_patch_applied_on": "",
          "v_patch_reverted_by": "",
          "v_patch_reverted_on": "",
          "v_patch_enforced_by": "",
          "v_patch_enforced_on": "",
          "v_patch_status": "",
          "acknowledged_date": "0001-01-01T00:00:00Z",
          "ack_scope": "",
          "ack_comment": "",
          "ack_author": "",
          "ack_expiration_days": 0,
          "ack_expiration_configured_at": "0001-01-01T00:00:00Z",
          "ack_expiration_configured_by": "",
          "v_patch_policy_name": "",
          "v_patch_policy_enforce": false,
          "audit_events_count": 0,
          "block_events_count": 0,
          "image_workload_info": null,
          "base_image_vulnerability": false,
          "base_image_name": ""
        },
        {
          "registry": "",
          "image_repository_name": "",
          "referenced_vulnerabilities": null,
          "resource": {
            "type": "",
            "format": "",
            "path": "",
            "name": "",
            "version": "",
            "arch": "",
            "cpe": "",
            "licenses": null,
            "hash": ""
          },
          "name": "CVE-2019-1348",
          "description": "An issue was found in Git before v2.24.1, v2.23.1, v2.22.2, v2.21.1, v2.20.2, v2.19.3, v2.18.2, v2.17.3, v2.16.6, v2.15.4, and v2.14.6. The --export-marks option of git fast-import is exposed also via the in-stream command feature export-marks=... and it allows overwriting arbitrary paths.",
          "publish_date": "2020-01-24",
          "modification_date": "2020-02-04",
          "vendor_severity": "low",
          "vendor_cvss2_score": 3.6,
          "vendor_cvss2_vectors": "AV:L/AC:L/Au:N/C:N/I:P/A:P",
          "vendor_cvss3_severity": "low",
          "vendor_cvss3_score": 3.3,
          "vendor_cvss3_vectors": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:L/A:N",
          "vendor_statement": "https://git.kernel.org/pub/scm/git/git.git/commit/?id=68061e3470210703cb15594194718d35094afdc0\nhttps://www.openwall.com/lists/oss-security/2019/12/13/1",
          "vendor_url": "https://security-tracker.debian.org/tracker/CVE-2019-1348",
          "nvd_severity": "low",
          "nvd_cvss2_score": 3.6,
          "nvd_cvss2_vectors": "AV:L/AC:L/Au:N/C:N/I:P/A:P",
          "nvd_cvss3_severity": "low",
          "nvd_cvss3_score": 3.3,
          "nvd_cvss3_vectors": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:L/A:N",
          "nvd_url": "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2019-1348",
          "fix_version": "",
          "solution": "",
          "classification": "",
          "qualys_ids": null,
          "aqua_score": 3.6,
          "aqua_severity": "low",
          "aqua_vectors": "AV:L/AC:L/Au:N/C:N/I:P/A:P",
          "aqua_scoring_system": "CVSS V2",
          "first_found_date": "2020-04-29",
          "last_found_date": "2020-04-29",
          "ancestor_pkg": "",
          "sibling_pkg": "",
          "v_patch_applied_by": "",
          "v_patch_applied_on": "",
          "v_patch_reverted_by": "",
          "v_patch_reverted_on": "",
          "v_patch_enforced_by": "",
          "v_patch_enforced_on": "",
          "v_patch_status": "",
          "acknowledged_date": "0001-01-01T00:00:00Z",
          "ack_scope": "",
          "ack_comment": "",
          "ack_author": "",
          "ack_expiration_days": 0,
          "ack_expiration_configured_at": "0001-01-01T00:00:00Z",
          "ack_expiration_configured_by": "",
          "v_patch_policy_name": "",
          "v_patch_policy_enforce": false,
          "audit_events_count": 0,
          "block_events_count": 0,
          "image_workload_info": null,
          "base_image_vulnerability": false,
          "base_image_name": ""
        }
      ],
      "resource": {
        "type": "package",
        "format": "deb",
        "path": "",
        "name": "git",
        "version": "1:2.11.0-3+deb9u4",
        "arch": "amd64",
        "cpe": "pkg:/debian:9:git:1:2.11.0-3+deb9u4",
        "licenses": null,
        "hash": ""
      },
      "name": "DSA-4581-1",
      "description": "",
      "publish_date": "",
      "modification_date": "",
      "vendor_severity": "high",
      "vendor_cvss2_score": 9.3,
      "vendor_cvss2_vectors": "AV:N/AC:M/Au:N/C:C/I:C/A:C",
      "vendor_statement": "",
      "vendor_url": "https://security-tracker.debian.org/tracker/DSA-4581-1",
      "nvd_severity": "high",
      "nvd_cvss2_score": 9.3,
      "nvd_cvss2_vectors": "AV:N/AC:M/Au:N/C:C/I:C/A:C",
      "nvd_cvss3_severity": "critical",
      "nvd_cvss3_score": 9.8,
      "nvd_cvss3_vectors": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
      "nvd_url": "",
      "fix_version": "1:2.11.0-3+deb9u5",
      "solution": "Upgrade package git to version 1:2.11.0-3+deb9u5 or above.",
      "classification": "",
      "qualys_ids": null,
      "aqua_score": 9.3,
      "aqua_severity": "critical",
      "aqua_vectors": "AV:N/AC:M/Au:N/C:C/I:C/A:C",
      "aqua_scoring_system": "CVSS V2",
      "first_found_date": "2020-04-29",
      "last_found_date": "2020-04-29",
      "ancestor_pkg": "",
      "sibling_pkg": "",
      "v_patch_applied_by": "",
      "v_patch_applied_on": "",
      "v_patch_reverted_by": "",
      "v_patch_reverted_on": "",
      "v_patch_enforced_by": "",
      "v_patch_enforced_on": "",
      "v_patch_status": "no_patch",
      "acknowledged_date": "1970-01-01T00:00:00Z",
      "ack_scope": "",
      "ack_comment": "",
      "ack_author": "",
      "ack_expiration_days": 0,
      "ack_expiration_configured_at": "1970-01-01T00:00:00Z",
      "ack_expiration_configured_by": "",
      "v_patch_policy_name": "",
      "v_patch_policy_enforce": false,
      "audit_events_count": 0,
      "block_events_count": 0,
      "image_workload_info": null,
      "base_image_vulnerability": false,
      "base_image_name": ""
    },
    {
      "registry": "Host Images",
      "image_repository_name": "gcr.io/google-containers/hyperkube",
      "image_name": "gcr.io/google-containers/hyperkube:v1.16.6",
      "image_digest": "sha256:ae6fea104d3daa8321f9ba27767b3f8f25eefc37d6cbfea7a611da15cacae153",
      "referenced_vulnerabilities": null,
      "resource": {
        "type": "file",
        "format": "",
        "path": "/usr/lib/python2.7/urllib.py",
        "name": "",
        "version": "",
        "arch": "",
        "cpe": "file:/aae56fa467741ad0d71b6ee3c037495d15735baf",
        "licenses": null,
        "hash": "sha1:aae56fa467741ad0d71b6ee3c037495d15735baf"
      },
      "name": "CVE-2019-9948",
      "description": "urllib in Python 2.x through 2.7.16 supports the local_file: scheme, which makes it easier for remote attackers to bypass protection mechanisms that blacklist file: URIs, as demonstrated by triggering a urllib.urlopen('local_file:///etc/passwd') call.",
      "publish_date": "2019-03-23",
      "modification_date": "2019-06-19",
      "vendor_severity": "high",
      "vendor_cvss2_score": 9.1,
      "vendor_cvss2_vectors": "",
      "vendor_statement": "",
      "vendor_url": "http://www.securityfocus.com/bid/107549",
      "nvd_severity": "medium",
      "nvd_cvss2_score": 6.4,
      "nvd_cvss2_vectors": "AV:N/AC:L/Au:N/C:P/I:P/A:N",
      "nvd_cvss3_severity": "critical",
      "nvd_cvss3_score": 9.1,
      "nvd_cvss3_vectors": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
      "nvd_url": "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2019-9948",
      "fix_version": "2.7.172.7, 3.5.73.5, 3.6.93.6, 3.7.43.7",
      "solution": "All Python 2.7.x users should upgrade to the latest version >= python-2.7.172.7\nAll Python 3.5.x users should upgrade to the latest version >= python-3.5.73.5/3.5m\nAll Python 3.6.x users should upgrade to the latest version >= python-3.6.93.6/3.6m\nAll Python 3.7x users should upgrade to the latest version >= python-3.7.43.7/3.7m",
      "classification": "",
      "qualys_ids": null,
      "aqua_score": 9.1,
      "aqua_severity": "critical",
      "aqua_vectors": "",
      "aqua_scoring_system": "CVSS V2",
      "first_found_date": "2020-04-29",
      "last_found_date": "2020-04-29",
      "ancestor_pkg": "",
      "sibling_pkg": "",
      "v_patch_applied_by": "",
      "v_patch_applied_on": "",
      "v_patch_reverted_by": "",
      "v_patch_reverted_on": "",
      "v_patch_enforced_by": "",
      "v_patch_enforced_on": "",
      "v_patch_status": "patch_available",
      "acknowledged_date": "1970-01-01T00:00:00Z",
      "ack_scope": "",
      "ack_comment": "",
      "ack_author": "",
      "ack_expiration_days": 0,
      "ack_expiration_configured_at": "1970-01-01T00:00:00Z",
      "ack_expiration_configured_by": "",
      "v_patch_policy_name": "",
      "v_patch_policy_enforce": false,
      "audit_events_count": 0,
      "block_events_count": 0,
      "image_workload_info": null,
      "base_image_vulnerability": false,
      "base_image_name": ""
    },
    {
      "registry": "Host Images",
      "image_repository_name": "quay.io/kubernetes-ingress-controller/nginx-ingress-controller",
      "image_name": "quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.26.1",
      "image_digest": "sha256:29024c9c6e706357bebda26ea9a15064e77616f4d40c215ce81ae5e4b2a460aa",
      "referenced_vulnerabilities": [
        {
          "registry": "",
          "image_repository_name": "",
          "referenced_vulnerabilities": null,
          "resource": {
            "type": "",
            "format": "",
            "path": "",
            "name": "",
            "version": "",
            "arch": "",
            "cpe": "",
            "licenses": null,
            "hash": ""
          },
          "name": "CVE-2019-5481",
          "description": "Double-free vulnerability in the FTP-kerberos code in cURL 7.52.0 to 7.65.3.",
          "publish_date": "2019-09-16",
          "modification_date": "2019-09-18",
          "vendor_severity": "high",
          "vendor_cvss2_score": 7.5,
          "vendor_cvss2_vectors": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
          "vendor_cvss3_severity": "critical",
          "vendor_cvss3_score": 9.8,
          "vendor_cvss3_vectors": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
          "vendor_statement": "https://curl.haxx.se/docs/CVE-2019-5481.html\nIntroduced by: https://github.com/curl/curl/commit/0649433da53c7165f839e24e889e131e2894dd32 (curl-7_52_0)\nFixed by: https://github.com/curl/curl/commit/9069838b30fb3b48af0123e39f664cea683254a5 (curl-7_66_0)",
          "vendor_url": "https://security-tracker.debian.org/tracker/CVE-2019-5481",
          "nvd_severity": "high",
          "nvd_cvss2_score": 7.5,
          "nvd_cvss2_vectors": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
          "nvd_cvss3_severity": "critical",
          "nvd_cvss3_score": 9.8,
          "nvd_cvss3_vectors": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
          "nvd_url": "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2019-5481",
          "fix_version": "",
          "solution": "",
          "classification": "",
          "qualys_ids": null,
          "aqua_score": 7.5,
          "aqua_severity": "high",
          "aqua_vectors": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
          "aqua_scoring_system": "CVSS V2",
          "first_found_date": "2020-04-29",
          "last_found_date": "2020-04-29",
          "ancestor_pkg": "",
          "sibling_pkg": "",
          "v_patch_applied_by": "",
          "v_patch_applied_on": "",
          "v_patch_reverted_by": "",
          "v_patch_reverted_on": "",
          "v_patch_enforced_by": "",
          "v_patch_enforced_on": "",
          "v_patch_status": "",
          "acknowledged_date": "0001-01-01T00:00:00Z",
          "ack_scope": "",
          "ack_comment": "",
          "ack_author": "",
          "ack_expiration_days": 0,
          "ack_expiration_configured_at": "0001-01-01T00:00:00Z",
          "ack_expiration_configured_by": "",
          "v_patch_policy_name": "",
          "v_patch_policy_enforce": false,
          "audit_events_count": 0,
          "block_events_count": 0,
          "image_workload_info": null,
          "base_image_vulnerability": false,
          "base_image_name": ""
        },
        {
          "registry": "",
          "image_repository_name": "",
          "referenced_vulnerabilities": null,
          "resource": {
            "type": "",
            "format": "",
            "path": "",
            "name": "",
            "version": "",
            "arch": "",
            "cpe": "",
            "licenses": null,
            "hash": ""
          },
          "name": "CVE-2019-5482",
          "description": "Heap buffer overflow in the TFTP protocol handler in cURL 7.19.4 to 7.65.3.",
          "publish_date": "2019-09-16",
          "modification_date": "2019-09-18",
          "vendor_severity": "high",
          "vendor_cvss2_score": 7.5,
          "vendor_cvss2_vectors": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
          "vendor_cvss3_severity": "critical",
          "vendor_cvss3_score": 9.8,
          "vendor_cvss3_vectors": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
          "vendor_statement": "https://curl.haxx.se/docs/CVE-2019-5482.html\nIntroduced by: https://github.com/curl/curl/commit/0516ce7786e9500c2e447d48aa9b3f24a6ca70f9\nFixed by: https://github.com/curl/curl/commit/facb0e4662415b5f28163e853dc6742ac5fafb3d (curl-7_66_0)",
          "vendor_url": "https://security-tracker.debian.org/tracker/CVE-2019-5482",
          "nvd_severity": "high",
          "nvd_cvss2_score": 7.5,
          "nvd_cvss2_vectors": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
          "nvd_cvss3_severity": "critical",
          "nvd_cvss3_score": 9.8,
          "nvd_cvss3_vectors": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
          "nvd_url": "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2019-5482",
          "fix_version": "",
          "solution": "",
          "classification": "",
          "qualys_ids": null,
          "aqua_score": 7.5,
          "aqua_severity": "high",
          "aqua_vectors": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
          "aqua_scoring_system": "CVSS V2",
          "first_found_date": "2020-04-29",
          "last_found_date": "2020-04-29",
          "ancestor_pkg": "",
          "sibling_pkg": "",
          "v_patch_applied_by": "",
          "v_patch_applied_on": "",
          "v_patch_reverted_by": "",
          "v_patch_reverted_on": "",
          "v_patch_enforced_by": "",
          "v_patch_enforced_on": "",
          "v_patch_status": "",
          "acknowledged_date": "0001-01-01T00:00:00Z",
          "ack_scope": "",
          "ack_comment": "",
          "ack_author": "",
          "ack_expiration_days": 0,
          "ack_expiration_configured_at": "0001-01-01T00:00:00Z",
          "ack_expiration_configured_by": "",
          "v_patch_policy_name": "",
          "v_patch_policy_enforce": false,
          "audit_events_count": 0,
          "block_events_count": 0,
          "image_workload_info": null,
          "base_image_vulnerability": false,
          "base_image_name": ""
        }
      ],
      "resource": {
        "type": "package",
        "format": "deb",
        "path": "",
        "name": "curl",
        "version": "7.64.0-4",
        "arch": "amd64",
        "cpe": "pkg:/debian:10:curl:7.64.0-4",
        "licenses": null,
        "hash": ""
      },
      "name": "DSA-4633-1",
      "description": "",
      "publish_date": "",
      "modification_date": "",
      "vendor_severity": "high",
      "vendor_cvss2_score": 7.5,
      "vendor_cvss2_vectors": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
      "vendor_statement": "",
      "vendor_url": "https://security-tracker.debian.org/tracker/DSA-4633-1",
      "nvd_severity": "high",
      "nvd_cvss2_score": 7.5,
      "nvd_cvss2_vectors": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
      "nvd_cvss3_severity": "critical",
      "nvd_cvss3_score": 9.8,
      "nvd_cvss3_vectors": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
      "nvd_url": "",
      "fix_version": "7.64.0-4+deb10u1",
      "solution": "Upgrade package curl to version 7.64.0-4+deb10u1 or above.",
      "classification": "",
      "qualys_ids": null,
      "aqua_score": 7.5,
      "aqua_severity": "high",
      "aqua_vectors": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
      "aqua_scoring_system": "CVSS V2",
      "first_found_date": "2020-04-29",
      "last_found_date": "2020-04-29",
      "ancestor_pkg": "",
      "sibling_pkg": "",
      "v_patch_applied_by": "",
      "v_patch_applied_on": "",
      "v_patch_reverted_by": "",
      "v_patch_reverted_on": "",
      "v_patch_enforced_by": "",
      "v_patch_enforced_on": "",
      "v_patch_status": "no_patch",
      "acknowledged_date": "1970-01-01T00:00:00Z",
      "ack_scope": "",
      "ack_comment": "",
      "ack_author": "",
      "ack_expiration_days": 0,
      "ack_expiration_configured_at": "1970-01-01T00:00:00Z",
      "ack_expiration_configured_by": "",
      "v_patch_policy_name": "",
      "v_patch_policy_enforce": false,
      "audit_events_count": 0,
      "block_events_count": 0,
      "image_workload_info": null,
      "base_image_vulnerability": false,
      "base_image_name": ""
    },
    {
      "registry": "Host Images",
      "image_repository_name": "digitalocean/do-csi-plugin",
      "image_name": "digitalocean/do-csi-plugin:v1.2.0",
      "image_digest": "sha256:84fa1763b48ad0a348676fa3bb893e759eb153febf399876af8926879d401fb1",
      "referenced_vulnerabilities": null,
      "resource": {
        "type": "package",
        "format": "apk",
        "path": "",
        "name": "musl",
        "version": "1.1.18-r3",
        "arch": "x86_64",
        "cpe": "pkg:/alpine:3.7.3:musl:1.1.18-r3",
        "licenses": [
          "MIT"
        ],
        "hash": ""
      },
      "name": "CVE-2019-14697",
      "description": "musl libc through 1.1.23 has an x87 floating-point stack adjustment imbalance, related to the math/i386/ directory. In some cases, use of this library could introduce out-of-bounds writes that are not present in an application's source code.",
      "publish_date": "2019-08-06",
      "modification_date": "2020-03-14",
      "vendor_severity": "high",
      "vendor_cvss2_score": 7.5,
      "vendor_cvss2_vectors": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
      "vendor_statement": "",
      "vendor_url": "",
      "nvd_severity": "high",
      "nvd_cvss2_score": 7.5,
      "nvd_cvss2_vectors": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
      "nvd_cvss3_severity": "critical",
      "nvd_cvss3_score": 9.8,
      "nvd_cvss3_vectors": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
      "nvd_url": "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2019-14697",
      "fix_version": "1.1.18-r4",
      "solution": "Upgrade package musl to version 1.1.18-r4 or above.",
      "classification": "",
      "qualys_ids": null,
      "aqua_score": 7.5,
      "aqua_severity": "high",
      "aqua_vectors": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
      "aqua_scoring_system": "CVSS V2",
      "first_found_date": "2020-04-29",
      "last_found_date": "2020-04-29",
      "ancestor_pkg": "",
      "sibling_pkg": "",
      "v_patch_applied_by": "",
      "v_patch_applied_on": "",
      "v_patch_reverted_by": "",
      "v_patch_reverted_on": "",
      "v_patch_enforced_by": "",
      "v_patch_enforced_on": "",
      "v_patch_status": "patch_available",
      "acknowledged_date": "1970-01-01T00:00:00Z",
      "ack_scope": "",
      "ack_comment": "",
      "ack_author": "",
      "ack_expiration_days": 0,
      "ack_expiration_configured_at": "1970-01-01T00:00:00Z",
      "ack_expiration_configured_by": "",
      "v_patch_policy_name": "",
      "v_patch_policy_enforce": false,
      "audit_events_count": 0,
      "block_events_count": 0,
      "image_workload_info": null,
      "base_image_vulnerability": false,
      "base_image_name": ""
    },
    {
      "registry": "Host Images",
      "image_repository_name": "quay.io/kubernetes-ingress-controller/nginx-ingress-controller",
      "image_name": "quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.26.1",
      "image_digest": "sha256:29024c9c6e706357bebda26ea9a15064e77616f4d40c215ce81ae5e4b2a460aa",
      "referenced_vulnerabilities": null,
      "resource": {
        "type": "package",
        "format": "deb",
        "path": "",
        "name": "libxml2",
        "version": "2.9.4+dfsg1-7+b3",
        "arch": "amd64",
        "cpe": "pkg:/debian:10:libxml2:2.9.4+dfsg1-7+b3",
        "licenses": null,
        "hash": ""
      },
      "name": "CVE-2020-3910",
      "description": "A buffer overflow was addressed with improved size validation. This issue is fixed in iOS 13.4 and iPadOS 13.4, macOS Catalina 10.15.4, tvOS 13.4, watchOS 6.2, iTunes for Windows 12.10.5, iCloud for Windows 10.9.3, iCloud for Windows 7.18. Multiple issues in libxml2.",
      "publish_date": "2020-04-01",
      "modification_date": "2020-04-02",
      "vendor_severity": "high",
      "vendor_cvss2_score": 7.5,
      "vendor_cvss2_vectors": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
      "vendor_statement": "",
      "vendor_url": "https://security-tracker.debian.org/tracker/CVE-2020-3910",
      "nvd_severity": "high",
      "nvd_cvss2_score": 7.5,
      "nvd_cvss2_vectors": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
      "nvd_cvss3_severity": "critical",
      "nvd_cvss3_score": 9.8,
      "nvd_cvss3_vectors": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
      "nvd_url": "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2020-3910",
      "fix_version": "",
      "solution": "",
      "classification": "The operating system vendor has not determined the vulnerability's impact yet, therefore NVD data has been used, if available",
      "qualys_ids": null,
      "aqua_score": 7.5,
      "aqua_severity": "high",
      "aqua_vectors": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
      "aqua_scoring_system": "CVSS V2",
      "first_found_date": "2020-04-29",
      "last_found_date": "2020-04-29",
      "ancestor_pkg": "",
      "sibling_pkg": "",
      "v_patch_applied_by": "",
      "v_patch_applied_on": "",
      "v_patch_reverted_by": "",
      "v_patch_reverted_on": "",
      "v_patch_enforced_by": "",
      "v_patch_enforced_on": "",
      "v_patch_status": "patch_available",
      "acknowledged_date": "1970-01-01T00:00:00Z",
      "ack_scope": "",
      "ack_comment": "",
      "ack_author": "",
      "ack_expiration_days": 0,
      "ack_expiration_configured_at": "1970-01-01T00:00:00Z",
      "ack_expiration_configured_by": "",
      "v_patch_policy_name": "",
      "v_patch_policy_enforce": false,
      "audit_events_count": 0,
      "block_events_count": 0,
      "image_workload_info": null,
      "base_image_vulnerability": false,
      "base_image_name": ""
    },
    {
      "registry": "Host Images",
      "image_repository_name": "quay.io/kubernetes-ingress-controller/nginx-ingress-controller",
      "image_name": "quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.26.1",
      "image_digest": "sha256:29024c9c6e706357bebda26ea9a15064e77616f4d40c215ce81ae5e4b2a460aa",
      "referenced_vulnerabilities": null,
      "resource": {
        "type": "package",
        "format": "deb",
        "path": "",
        "name": "libxml2",
        "version": "2.9.4+dfsg1-7+b3",
        "arch": "amd64",
        "cpe": "pkg:/debian:10:libxml2:2.9.4+dfsg1-7+b3",
        "licenses": null,
        "hash": ""
      },
      "name": "CVE-2020-3909",
      "description": "A buffer overflow was addressed with improved bounds checking. This issue is fixed in iOS 13.4 and iPadOS 13.4, macOS Catalina 10.15.4, tvOS 13.4, watchOS 6.2, iTunes for Windows 12.10.5, iCloud for Windows 10.9.3, iCloud for Windows 7.18. Multiple issues in libxml2.",
      "publish_date": "2020-04-01",
      "modification_date": "2020-04-02",
      "vendor_severity": "high",
      "vendor_cvss2_score": 7.5,
      "vendor_cvss2_vectors": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
      "vendor_statement": "",
      "vendor_url": "https://security-tracker.debian.org/tracker/CVE-2020-3909",
      "nvd_severity": "high",
      "nvd_cvss2_score": 7.5,
      "nvd_cvss2_vectors": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
      "nvd_cvss3_severity": "critical",
      "nvd_cvss3_score": 9.8,
      "nvd_cvss3_vectors": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
      "nvd_url": "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2020-3909",
      "fix_version": "",
      "solution": "",
      "classification": "The operating system vendor has not determined the vulnerability's impact yet, therefore NVD data has been used, if available",
      "qualys_ids": null,
      "aqua_score": 7.5,
      "aqua_severity": "high",
      "aqua_vectors": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
      "aqua_scoring_system": "CVSS V2",
      "first_found_date": "2020-04-29",
      "last_found_date": "2020-04-29",
      "ancestor_pkg": "",
      "sibling_pkg": "",
      "v_patch_applied_by": "",
      "v_patch_applied_on": "",
      "v_patch_reverted_by": "",
      "v_patch_reverted_on": "",
      "v_patch_enforced_by": "",
      "v_patch_enforced_on": "",
      "v_patch_status": "patch_available",
      "acknowledged_date": "1970-01-01T00:00:00Z",
      "ack_scope": "",
      "ack_comment": "",
      "ack_author": "",
      "ack_expiration_days": 0,
      "ack_expiration_configured_at": "1970-01-01T00:00:00Z",
      "ack_expiration_configured_by": "",
      "v_patch_policy_name": "",
      "v_patch_policy_enforce": false,
      "audit_events_count": 0,
      "block_events_count": 0,
      "image_workload_info": null,
      "base_image_vulnerability": false,
      "base_image_name": ""
    },
    {
      "registry": "Host Images",
      "image_repository_name": "gcr.io/google-containers/hyperkube",
      "image_name": "gcr.io/google-containers/hyperkube:v1.16.6",
      "image_digest": "sha256:ae6fea104d3daa8321f9ba27767b3f8f25eefc37d6cbfea7a611da15cacae153",
      "referenced_vulnerabilities": null,
      "resource": {
        "type": "file",
        "format": "",
        "path": "/usr/lib/python2.7/email/_parseaddr.py",
        "name": "",
        "version": "",
        "arch": "",
        "cpe": "file:/7b3eea299ef71488408280fea80bbdc8f926a603",
        "licenses": null,
        "hash": "sha1:7b3eea299ef71488408280fea80bbdc8f926a603"
      },
      "name": "CVE-2019-16056",
      "description": "An issue was discovered in Python through 2.7.16, 3.x through 3.5.7, 3.6.x through 3.6.9, and 3.7.x through 3.7.4. The email module wrongly parses email addresses that contain multiple @ characters. An application that uses the email module and implements some kind of checks on the From/To headers of a message could be tricked into accepting an email address that should be denied. An attack may be the same as in CVE-2019-11340; however, this CVE applies to Python more generally.",
      "publish_date": "2019-09-06",
      "modification_date": "2019-09-11",
      "vendor_severity": "high",
      "vendor_cvss2_score": 7.5,
      "vendor_cvss2_vectors": "",
      "vendor_statement": "",
      "vendor_url": "https://bugs.python.org/issue34155",
      "nvd_severity": "medium",
      "nvd_cvss2_score": 5,
      "nvd_cvss2_vectors": "AV:N/AC:L/Au:N/C:P/I:N/A:N",
      "nvd_cvss3_severity": "high",
      "nvd_cvss3_score": 7.5,
      "nvd_cvss3_vectors": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
      "nvd_url": "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2019-16056",
      "fix_version": "",
      "solution": "",
      "classification": "",
      "qualys_ids": null,
      "aqua_score": 7.5,
      "aqua_severity": "high",
      "aqua_vectors": "",
      "aqua_scoring_system": "CVSS V2",
      "first_found_date": "2020-04-29",
      "last_found_date": "2020-04-29",
      "ancestor_pkg": "",
      "sibling_pkg": "",
      "v_patch_applied_by": "",
      "v_patch_applied_on": "",
      "v_patch_reverted_by": "",
      "v_patch_reverted_on": "",
      "v_patch_enforced_by": "",
      "v_patch_enforced_on": "",
      "v_patch_status": "patch_available",
      "acknowledged_date": "1970-01-01T00:00:00Z",
      "ack_scope": "",
      "ack_comment": "",
      "ack_author": "",
      "ack_expiration_days": 0,
      "ack_expiration_configured_at": "1970-01-01T00:00:00Z",
      "ack_expiration_configured_by": "",
      "v_patch_policy_name": "",
      "v_patch_policy_enforce": false,
      "audit_events_count": 0,
      "block_events_count": 0,
      "image_workload_info": null,
      "base_image_vulnerability": false,
      "base_image_name": ""
    },
    {
      "registry": "Host Images",
      "image_repository_name": "gcr.io/google-containers/hyperkube",
      "image_name": "gcr.io/google-containers/hyperkube:v1.16.6",
      "image_digest": "sha256:ae6fea104d3daa8321f9ba27767b3f8f25eefc37d6cbfea7a611da15cacae153",
      "referenced_vulnerabilities": null,
      "resource": {
        "type": "package",
        "format": "deb",
        "path": "",
        "name": "libxml2",
        "version": "2.9.4+dfsg1-2.2+deb9u2",
        "arch": "amd64",
        "cpe": "pkg:/debian:9:libxml2:2.9.4+dfsg1-2.2+deb9u2",
        "licenses": null,
        "hash": ""
      },
      "name": "CVE-2020-3909",
      "description": "A buffer overflow was addressed with improved bounds checking. This issue is fixed in iOS 13.4 and iPadOS 13.4, macOS Catalina 10.15.4, tvOS 13.4, watchOS 6.2, iTunes for Windows 12.10.5, iCloud for Windows 10.9.3, iCloud for Windows 7.18. Multiple issues in libxml2.",
      "publish_date": "2020-04-01",
      "modification_date": "2020-04-02",
      "vendor_severity": "high",
      "vendor_cvss2_score": 7.5,
      "vendor_cvss2_vectors": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
      "vendor_statement": "",
      "vendor_url": "https://security-tracker.debian.org/tracker/CVE-2020-3909",
      "nvd_severity": "high",
      "nvd_cvss2_score": 7.5,
      "nvd_cvss2_vectors": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
      "nvd_cvss3_severity": "critical",
      "nvd_cvss3_score": 9.8,
      "nvd_cvss3_vectors": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
      "nvd_url": "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2020-3909",
      "fix_version": "",
      "solution": "",
      "classification": "The operating system vendor has not determined the vulnerability's impact yet, therefore NVD data has been used, if available",
      "qualys_ids": null,
      "aqua_score": 7.5,
      "aqua_severity": "high",
      "aqua_vectors": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
      "aqua_scoring_system": "CVSS V2",
      "first_found_date": "2020-04-29",
      "last_found_date": "2020-04-29",
      "ancestor_pkg": "",
      "sibling_pkg": "",
      "v_patch_applied_by": "",
      "v_patch_applied_on": "",
      "v_patch_reverted_by": "",
      "v_patch_reverted_on": "",
      "v_patch_enforced_by": "",
      "v_patch_enforced_on": "",
      "v_patch_status": "patch_available",
      "acknowledged_date": "1970-01-01T00:00:00Z",
      "ack_scope": "",
      "ack_comment": "",
      "ack_author": "",
      "ack_expiration_days": 0,
      "ack_expiration_configured_at": "1970-01-01T00:00:00Z",
      "ack_expiration_configured_by": "",
      "v_patch_policy_name": "",
      "v_patch_policy_enforce": false,
      "audit_events_count": 0,
      "block_events_count": 0,
      "image_workload_info": null,
      "base_image_vulnerability": false,
      "base_image_name": ""
    },
    {
      "registry": "Host Images",
      "image_repository_name": "gcr.io/google-containers/hyperkube",
      "image_name": "gcr.io/google-containers/hyperkube:v1.16.6",
      "image_digest": "sha256:ae6fea104d3daa8321f9ba27767b3f8f25eefc37d6cbfea7a611da15cacae153",
      "referenced_vulnerabilities": null,
      "resource": {
        "type": "package",
        "format": "deb",
        "path": "",
        "name": "libxml2",
        "version": "2.9.4+dfsg1-2.2+deb9u2",
        "arch": "amd64",
        "cpe": "pkg:/debian:9:libxml2:2.9.4+dfsg1-2.2+deb9u2",
        "licenses": null,
        "hash": ""
      },
      "name": "CVE-2020-3910",
      "description": "A buffer overflow was addressed with improved size validation. This issue is fixed in iOS 13.4 and iPadOS 13.4, macOS Catalina 10.15.4, tvOS 13.4, watchOS 6.2, iTunes for Windows 12.10.5, iCloud for Windows 10.9.3, iCloud for Windows 7.18. Multiple issues in libxml2.",
      "publish_date": "2020-04-01",
      "modification_date": "2020-04-02",
      "vendor_severity": "high",
      "vendor_cvss2_score": 7.5,
      "vendor_cvss2_vectors": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
      "vendor_statement": "",
      "vendor_url": "https://security-tracker.debian.org/tracker/CVE-2020-3910",
      "nvd_severity": "high",
      "nvd_cvss2_score": 7.5,
      "nvd_cvss2_vectors": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
      "nvd_cvss3_severity": "critical",
      "nvd_cvss3_score": 9.8,
      "nvd_cvss3_vectors": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
      "nvd_url": "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2020-3910",
      "fix_version": "",
      "solution": "",
      "classification": "The operating system vendor has not determined the vulnerability's impact yet, therefore NVD data has been used, if available",
      "qualys_ids": null,
      "aqua_score": 7.5,
      "aqua_severity": "high",
      "aqua_vectors": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
      "aqua_scoring_system": "CVSS V2",
      "first_found_date": "2020-04-29",
      "last_found_date": "2020-04-29",
      "ancestor_pkg": "",
      "sibling_pkg": "",
      "v_patch_applied_by": "",
      "v_patch_applied_on": "",
      "v_patch_reverted_by": "",
      "v_patch_reverted_on": "",
      "v_patch_enforced_by": "",
      "v_patch_enforced_on": "",
      "v_patch_status": "patch_available",
      "acknowledged_date": "1970-01-01T00:00:00Z",
      "ack_scope": "",
      "ack_comment": "",
      "ack_author": "",
      "ack_expiration_days": 0,
      "ack_expiration_configured_at": "1970-01-01T00:00:00Z",
      "ack_expiration_configured_by": "",
      "v_patch_policy_name": "",
      "v_patch_policy_enforce": false,
      "audit_events_count": 0,
      "block_events_count": 0,
      "image_workload_info": null,
      "base_image_vulnerability": false,
      "base_image_name": ""
    },
    {
      "registry": "Host Images",
      "image_repository_name": "registry.aquasec.com/database",
      "image_name": "registry.aquasec.com/database:4.6",
      "image_digest": "sha256:68e030c35a660b30c2a0e45cee342f951905cd47f62aec257fd6256657403fd8",
      "referenced_vulnerabilities": null,
      "resource": {
        "type": "package",
        "format": "apk",
        "path": "",
        "name": "bash",
        "version": "4.4.19-r1",
        "arch": "x86_64",
        "cpe": "pkg:/alpine:3.9.3:bash:4.4.19-r1",
        "licenses": [
          "GPL3orlater"
        ],
        "hash": ""
      },
      "name": "CVE-2019-18276",
      "description": "An issue was discovered in disable_priv_mode in shell.c in GNU Bash through 5.0 patch 11. By default, if Bash is run with its effective UID not equal to its real UID, it will drop privileges by setting its effective UID to its real UID. However, it does so incorrectly. On Linux and other systems that support \"saved UID\" functionality, the saved UID is not dropped. An attacker with command execution in the shell can use \"enable -f\" for runtime loading of a new builtin, which can be a shared object that calls setuid() and therefore regains privileges. However, binaries running with an effective UID of 0 are unaffected.",
      "publish_date": "2019-11-28",
      "modification_date": "2020-01-22",
      "vendor_severity": "high",
      "vendor_cvss2_score": 7.2,
      "vendor_cvss2_vectors": "AV:L/AC:L/Au:N/C:C/I:C/A:C",
      "vendor_statement": "",
      "vendor_url": "",
      "nvd_severity": "high",
      "nvd_cvss2_score": 7.2,
      "nvd_cvss2_vectors": "AV:L/AC:L/Au:N/C:C/I:C/A:C",
      "nvd_cvss3_severity": "high",
      "nvd_cvss3_score": 7.8,
      "nvd_cvss3_vectors": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
      "nvd_url": "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2019-18276",
      "fix_version": "",
      "solution": "",
      "classification": "",
      "qualys_ids": null,
      "aqua_score": 7.2,
      "aqua_severity": "high",
      "aqua_vectors": "AV:L/AC:L/Au:N/C:C/I:C/A:C",
      "aqua_scoring_system": "CVSS V2",
      "first_found_date": "2020-04-29",
      "last_found_date": "2020-04-29",
      "ancestor_pkg": "",
      "sibling_pkg": "",
      "v_patch_applied_by": "",
      "v_patch_applied_on": "",
      "v_patch_reverted_by": "",
      "v_patch_reverted_on": "",
      "v_patch_enforced_by": "",
      "v_patch_enforced_on": "",
      "v_patch_status": "no_patch",
      "acknowledged_date": "1970-01-01T00:00:00Z",
      "ack_scope": "",
      "ack_comment": "",
      "ack_author": "",
      "ack_expiration_days": 0,
      "ack_expiration_configured_at": "1970-01-01T00:00:00Z",
      "ack_expiration_configured_by": "",
      "v_patch_policy_name": "",
      "v_patch_policy_enforce": false,
      "audit_events_count": 0,
      "block_events_count": 0,
      "image_workload_info": null,
      "base_image_vulnerability": false,
      "base_image_name": ""
    },
    {
      "registry": "Host Images",
      "image_repository_name": "registry.aquasec.com/enforcer",
      "image_name": "registry.aquasec.com/enforcer:4.6",
      "image_digest": "sha256:39931a1c9fd34dbfab0d51bf20992c3b70228d3142056840024219eaccd1e160",
      "referenced_vulnerabilities": null,
      "resource": {
        "type": "package",
        "format": "apk",
        "path": "",
        "name": "libarchive",
        "version": "3.3.3-r1",
        "arch": "x86_64",
        "cpe": "pkg:/alpine:3.7.3:libarchive:3.3.3-r1",
        "licenses": [
          "BSD"
        ],
        "hash": ""
      },
      "name": "CVE-2018-1000877",
      "description": "libarchive version commit 416694915449219d505531b1096384f3237dd6cc onwards (release v3.1.0 onwards) contains a CWE-415: Double Free vulnerability in RAR decoder - libarchive/archive_read_support_format_rar.c, parse_codes(), realloc(rar->lzss.window, new_size) with new_size = 0 that can result in Crash/DoS. This attack appear to be exploitable via the victim must open a specially crafted RAR archive.",
      "publish_date": "2018-12-20",
      "modification_date": "2019-11-06",
      "vendor_severity": "medium",
      "vendor_cvss2_score": 6.8,
      "vendor_cvss2_vectors": "AV:N/AC:M/Au:N/C:P/I:P/A:P",
      "vendor_statement": "",
      "vendor_url": "",
      "nvd_severity": "medium",
      "nvd_cvss2_score": 6.8,
      "nvd_cvss2_vectors": "AV:N/AC:M/Au:N/C:P/I:P/A:P",
      "nvd_cvss3_severity": "high",
      "nvd_cvss3_score": 8.8,
      "nvd_cvss3_vectors": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
      "nvd_url": "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2018-1000877",
      "fix_version": "",
      "solution": "",
      "classification": "",
      "qualys_ids": null,
      "aqua_score": 6.8,
      "aqua_severity": "medium",
      "aqua_vectors": "AV:N/AC:M/Au:N/C:P/I:P/A:P",
      "aqua_scoring_system": "CVSS V2",
      "first_found_date": "2020-04-29",
      "last_found_date": "2020-04-29",
      "ancestor_pkg": "",
      "sibling_pkg": "",
      "v_patch_applied_by": "",
      "v_patch_applied_on": "",
      "v_patch_reverted_by": "",
      "v_patch_reverted_on": "",
      "v_patch_enforced_by": "",
      "v_patch_enforced_on": "",
      "v_patch_status": "no_patch",
      "acknowledged_date": "1970-01-01T00:00:00Z",
      "ack_scope": "",
      "ack_comment": "",
      "ack_author": "",
      "ack_expiration_days": 0,
      "ack_expiration_configured_at": "1970-01-01T00:00:00Z",
      "ack_expiration_configured_by": "",
      "v_patch_policy_name": "",
      "v_patch_policy_enforce": false,
      "audit_events_count": 0,
      "block_events_count": 0,
      "image_workload_info": null,
      "base_image_vulnerability": false,
      "base_image_name": ""
    },
    {
      "registry": "Host Images",
      "image_repository_name": "registry.aquasec.com/enforcer",
      "image_name": "registry.aquasec.com/enforcer:4.6",
      "image_digest": "sha256:39931a1c9fd34dbfab0d51bf20992c3b70228d3142056840024219eaccd1e160",
      "referenced_vulnerabilities": null,
      "resource": {
        "type": "package",
        "format": "apk",
        "path": "",
        "name": "libarchive",
        "version": "3.3.3-r1",
        "arch": "x86_64",
        "cpe": "pkg:/alpine:3.7.3:libarchive:3.3.3-r1",
        "licenses": [
          "BSD"
        ],
        "hash": ""
      },
      "name": "CVE-2018-1000878",
      "description": "libarchive version commit 416694915449219d505531b1096384f3237dd6cc onwards (release v3.1.0 onwards) contains a CWE-416: Use After Free vulnerability in RAR decoder - libarchive/archive_read_support_format_rar.c that can result in Crash/DoS - it is unknown if RCE is possible. This attack appear to be exploitable via the victim must open a specially crafted RAR archive.",
      "publish_date": "2018-12-20",
      "modification_date": "2019-11-06",
      "vendor_severity": "medium",
      "vendor_cvss2_score": 6.8,
      "vendor_cvss2_vectors": "AV:N/AC:M/Au:N/C:P/I:P/A:P",
      "vendor_statement": "",
      "vendor_url": "",
      "nvd_severity": "medium",
      "nvd_cvss2_score": 6.8,
      "nvd_cvss2_vectors": "AV:N/AC:M/Au:N/C:P/I:P/A:P",
      "nvd_cvss3_severity": "high",
      "nvd_cvss3_score": 8.8,
      "nvd_cvss3_vectors": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
      "nvd_url": "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2018-1000878",
      "fix_version": "",
      "solution": "",
      "classification": "",
      "qualys_ids": null,
      "aqua_score": 6.8,
      "aqua_severity": "medium",
      "aqua_vectors": "AV:N/AC:M/Au:N/C:P/I:P/A:P",
      "aqua_scoring_system": "CVSS V2",
      "first_found_date": "2020-04-29",
      "last_found_date": "2020-04-29",
      "ancestor_pkg": "",
      "sibling_pkg": "",
      "v_patch_applied_by": "",
      "v_patch_applied_on": "",
      "v_patch_reverted_by": "",
      "v_patch_reverted_on": "",
      "v_patch_enforced_by": "",
      "v_patch_enforced_on": "",
      "v_patch_status": "no_patch",
      "acknowledged_date": "1970-01-01T00:00:00Z",
      "ack_scope": "",
      "ack_comment": "",
      "ack_author": "",
      "ack_expiration_days": 0,
      "ack_expiration_configured_at": "1970-01-01T00:00:00Z",
      "ack_expiration_configured_by": "",
      "v_patch_policy_name": "",
      "v_patch_policy_enforce": false,
      "audit_events_count": 0,
      "block_events_count": 0,
      "image_workload_info": null,
      "base_image_vulnerability": false,
      "base_image_name": ""
    },
    {
      "registry": "Host Images",
      "image_repository_name": "registry.aquasec.com/enforcer",
      "image_name": "registry.aquasec.com/enforcer:4.6",
      "image_digest": "sha256:39931a1c9fd34dbfab0d51bf20992c3b70228d3142056840024219eaccd1e160",
      "referenced_vulnerabilities": null,
      "resource": {
        "type": "package",
        "format": "apk",
        "path": "",
        "name": "libarchive",
        "version": "3.3.3-r1",
        "arch": "x86_64",
        "cpe": "pkg:/alpine:3.7.3:libarchive:3.3.3-r1",
        "licenses": [
          "BSD"
        ],
        "hash": ""
      },
      "name": "CVE-2020-9308",
      "description": "archive_read_support_format_rar5.c in libarchive before 3.4.2 attempts to unpack a RAR5 file with an invalid or corrupted header (such as a header size of zero), leading to a SIGSEGV or possibly unspecified other impact.",
      "publish_date": "2020-02-20",
      "modification_date": "2020-03-15",
      "vendor_severity": "medium",
      "vendor_cvss2_score": 6.8,
      "vendor_cvss2_vectors": "AV:N/AC:M/Au:N/C:P/I:P/A:P",
      "vendor_statement": "",
      "vendor_url": "",
      "nvd_severity": "medium",
      "nvd_cvss2_score": 6.8,
      "nvd_cvss2_vectors": "AV:N/AC:M/Au:N/C:P/I:P/A:P",
      "nvd_cvss3_severity": "high",
      "nvd_cvss3_score": 8.8,
      "nvd_cvss3_vectors": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
      "nvd_url": "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2020-9308",
      "fix_version": "",
      "solution": "",
      "classification": "",
      "qualys_ids": null,
      "aqua_score": 6.8,
      "aqua_severity": "medium",
      "aqua_vectors": "AV:N/AC:M/Au:N/C:P/I:P/A:P",
      "aqua_scoring_system": "CVSS V2",
      "first_found_date": "2020-04-29",
      "last_found_date": "2020-04-29",
      "ancestor_pkg": "",
      "sibling_pkg": "",
      "v_patch_applied_by": "",
      "v_patch_applied_on": "",
      "v_patch_reverted_by": "",
      "v_patch_reverted_on": "",
      "v_patch_enforced_by": "",
      "v_patch_enforced_on": "",
      "v_patch_status": "no_patch",
      "acknowledged_date": "1970-01-01T00:00:00Z",
      "ack_scope": "",
      "ack_comment": "",
      "ack_author": "",
      "ack_expiration_days": 0,
      "ack_expiration_configured_at": "1970-01-01T00:00:00Z",
      "ack_expiration_configured_by": "",
      "v_patch_policy_name": "",
      "v_patch_policy_enforce": false,
      "audit_events_count": 0,
      "block_events_count": 0,
      "image_workload_info": null,
      "base_image_vulnerability": false,
      "base_image_name": ""
    },
    {
      "registry": "Host Images",
      "image_repository_name": "gcr.io/google-containers/hyperkube",
      "image_name": "gcr.io/google-containers/hyperkube:v1.16.6",
      "image_digest": "sha256:ae6fea104d3daa8321f9ba27767b3f8f25eefc37d6cbfea7a611da15cacae153",
      "referenced_vulnerabilities": null,
      "resource": {
        "type": "file",
        "format": "",
        "path": "/usr/lib/python2.7/DocXMLRPCServer.py",
        "name": "",
        "version": "",
        "arch": "",
        "cpe": "file:/38e204c95da95e4a1e1518db76adc94f64c69ddb",
        "licenses": null,
        "hash": "sha1:38e204c95da95e4a1e1518db76adc94f64c69ddb"
      },
      "name": "CVE-2019-16935",
      "description": "The documentation XML-RPC server in Python through 2.7.16, 3.x through 3.6.9, and 3.7.x through 3.7.4 has XSS via the server_title field. This occurs in Lib/DocXMLRPCServer.py in Python 2.x, and in Lib/xmlrpc/server.py in Python 3.x. If set_server_title is called with untrusted input, arbitrary JavaScript can be delivered to clients that visit the http URL for this server.",
      "publish_date": "2019-09-28",
      "modification_date": "2019-10-09",
      "vendor_severity": "medium",
      "vendor_cvss2_score": 6.1,
      "vendor_cvss2_vectors": "",
      "vendor_statement": "",
      "vendor_url": "https://bugs.python.org/issue38243",
      "nvd_severity": "medium",
      "nvd_cvss2_score": 4.3,
      "nvd_cvss2_vectors": "AV:N/AC:M/Au:N/C:N/I:P/A:N",
      "nvd_cvss3_severity": "medium",
      "nvd_cvss3_score": 6.1,
      "nvd_cvss3_vectors": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
      "nvd_url": "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2019-16935",
      "fix_version": "3.7.5rc1",
      "solution": "v3.7.5rc1",
      "classification": "",
      "qualys_ids": null,
      "aqua_score": 6.1,
      "aqua_severity": "medium",
      "aqua_vectors": "",
      "aqua_scoring_system": "CVSS V2",
      "first_found_date": "2020-04-29",
      "last_found_date": "2020-04-29",
      "ancestor_pkg": "",
      "sibling_pkg": "",
      "v_patch_applied_by": "",
      "v_patch_applied_on": "",
      "v_patch_reverted_by": "",
      "v_patch_reverted_on": "",
      "v_patch_enforced_by": "",
      "v_patch_enforced_on": "",
      "v_patch_status": "patch_available",
      "acknowledged_date": "1970-01-01T00:00:00Z",
      "ack_scope": "",
      "ack_comment": "",
      "ack_author": "",
      "ack_expiration_days": 0,
      "ack_expiration_configured_at": "1970-01-01T00:00:00Z",
      "ack_expiration_configured_by": "",
      "v_patch_policy_name": "",
      "v_patch_policy_enforce": false,
      "audit_events_count": 0,
      "block_events_count": 0,
      "image_workload_info": null,
      "base_image_vulnerability": false,
      "base_image_name": ""
    },
    {
      "registry": "Host Images",
      "image_repository_name": "gcr.io/google-containers/hyperkube",
      "image_name": "gcr.io/google-containers/hyperkube:v1.16.6",
      "image_digest": "sha256:ae6fea104d3daa8321f9ba27767b3f8f25eefc37d6cbfea7a611da15cacae153",
      "referenced_vulnerabilities": null,
      "resource": {
        "type": "file",
        "format": "",
        "path": "/usr/lib/python2.7/dist-packages/urllib3/util/url.py",
        "name": "",
        "version": "",
        "arch": "",
        "cpe": "file:/96a6cf9fcc3c06ed4122afecf4ddc8468c9d00cf",
        "licenses": null,
        "hash": "sha1:96a6cf9fcc3c06ed4122afecf4ddc8468c9d00cf"
      },
      "name": "CVE-2019-9740",
      "description": "An issue was discovered in urllib2 in Python 2.x through 2.7.16 and urllib in Python 3.x through 3.7.3. CRLF injection is possible if the attacker controls a url parameter, as demonstrated by the first argument to urllib.request.urlopen with \\r\\n (specifically in the query string after a ? character) followed by an HTTP header or a Redis command.",
      "publish_date": "2019-03-13",
      "modification_date": "2019-05-28",
      "vendor_severity": "medium",
      "vendor_cvss2_score": 6.1,
      "vendor_cvss2_vectors": "",
      "vendor_statement": "",
      "vendor_url": "http://www.securityfocus.com/bid/107466",
      "nvd_severity": "medium",
      "nvd_cvss2_score": 4.3,
      "nvd_cvss2_vectors": "AV:N/AC:M/Au:N/C:N/I:P/A:N",
      "nvd_cvss3_severity": "medium",
      "nvd_cvss3_score": 6.1,
      "nvd_cvss3_vectors": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
      "nvd_url": "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2019-9740",
      "fix_version": "2.7.172.7, 3.5.73.5, 3.6.93.6, 3.7.43.7",
      "solution": "3.7.4\nAll Python 2.7.x users should upgrade to the latest version >= python-2.7.172.7\nAll Python 3.5.x users should upgrade to the latest version >= python-3.5.73.5/3.5m\nAll Python 3.6.x users should upgrade to the latest version >= python-3.6.93.6/3.6m\nAll Python 3.7x users should upgrade to the latest version >= python-3.7.43.7/3.7m",
      "classification": "",
      "qualys_ids": null,
      "aqua_score": 6.1,
      "aqua_severity": "medium",
      "aqua_vectors": "",
      "aqua_scoring_system": "CVSS V2",
      "first_found_date": "2020-04-29",
      "last_found_date": "2020-04-29",
      "ancestor_pkg": "",
      "sibling_pkg": "",
      "v_patch_applied_by": "",
      "v_patch_applied_on": "",
      "v_patch_reverted_by": "",
      "v_patch_reverted_on": "",
      "v_patch_enforced_by": "",
      "v_patch_enforced_on": "",
      "v_patch_status": "patch_available",
      "acknowledged_date": "1970-01-01T00:00:00Z",
      "ack_scope": "",
      "ack_comment": "",
      "ack_author": "",
      "ack_expiration_days": 0,
      "ack_expiration_configured_at": "1970-01-01T00:00:00Z",
      "ack_expiration_configured_by": "",
      "v_patch_policy_name": "",
      "v_patch_policy_enforce": false,
      "audit_events_count": 0,
      "block_events_count": 0,
      "image_workload_info": null,
      "base_image_vulnerability": false,
      "base_image_name": ""
    },
    {
      "registry": "Host Images",
      "image_repository_name": "gcr.io/google-containers/hyperkube",
      "image_name": "gcr.io/google-containers/hyperkube:v1.16.6",
      "image_digest": "sha256:ae6fea104d3daa8321f9ba27767b3f8f25eefc37d6cbfea7a611da15cacae153",
      "referenced_vulnerabilities": null,
      "resource": {
        "type": "file",
        "format": "",
        "path": "/usr/lib/python2.7/httplib.py",
        "name": "",
        "version": "",
        "arch": "",
        "cpe": "file:/ec20a4287fb780da10392fc732c387076c348b4b",
        "licenses": null,
        "hash": "sha1:ec20a4287fb780da10392fc732c387076c348b4b"
      },
      "name": "CVE-2019-9740",
      "description": "An issue was discovered in urllib2 in Python 2.x through 2.7.16 and urllib in Python 3.x through 3.7.3. CRLF injection is possible if the attacker controls a url parameter, as demonstrated by the first argument to urllib.request.urlopen with \\r\\n (specifically in the query string after a ? character) followed by an HTTP header or a Redis command.",
      "publish_date": "2019-03-13",
      "modification_date": "2019-05-28",
      "vendor_severity": "medium",
      "vendor_cvss2_score": 6.1,
      "vendor_cvss2_vectors": "",
      "vendor_statement": "",
      "vendor_url": "http://www.securityfocus.com/bid/107466",
      "nvd_severity": "medium",
      "nvd_cvss2_score": 4.3,
      "nvd_cvss2_vectors": "AV:N/AC:M/Au:N/C:N/I:P/A:N",
      "nvd_cvss3_severity": "medium",
      "nvd_cvss3_score": 6.1,
      "nvd_cvss3_vectors": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
      "nvd_url": "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2019-9740",
      "fix_version": "2.7.172.7, 3.5.73.5, 3.6.93.6, 3.7.43.7",
      "solution": "3.7.4\nAll Python 2.7.x users should upgrade to the latest version >= python-2.7.172.7\nAll Python 3.5.x users should upgrade to the latest version >= python-3.5.73.5/3.5m\nAll Python 3.6.x users should upgrade to the latest version >= python-3.6.93.6/3.6m\nAll Python 3.7x users should upgrade to the latest version >= python-3.7.43.7/3.7m",
      "classification": "",
      "qualys_ids": null,
      "aqua_score": 6.1,
      "aqua_severity": "medium",
      "aqua_vectors": "",
      "aqua_scoring_system": "CVSS V2",
      "first_found_date": "2020-04-29",
      "last_found_date": "2020-04-29",
      "ancestor_pkg": "",
      "sibling_pkg": "",
      "v_patch_applied_by": "",
      "v_patch_applied_on": "",
      "v_patch_reverted_by": "",
      "v_patch_reverted_on": "",
      "v_patch_enforced_by": "",
      "v_patch_enforced_on": "",
      "v_patch_status": "patch_available",
      "acknowledged_date": "1970-01-01T00:00:00Z",
      "ack_scope": "",
      "ack_comment": "",
      "ack_author": "",
      "ack_expiration_days": 0,
      "ack_expiration_configured_at": "1970-01-01T00:00:00Z",
      "ack_expiration_configured_by": "",
      "v_patch_policy_name": "",
      "v_patch_policy_enforce": false,
      "audit_events_count": 0,
      "block_events_count": 0,
      "image_workload_info": null,
      "base_image_vulnerability": false,
      "base_image_name": ""
    },
    {
      "registry": "Host Images",
      "image_repository_name": "gcr.io/google-containers/hyperkube",
      "image_name": "gcr.io/google-containers/hyperkube:v1.16.6",
      "image_digest": "sha256:ae6fea104d3daa8321f9ba27767b3f8f25eefc37d6cbfea7a611da15cacae153",
      "referenced_vulnerabilities": null,
      "resource": {
        "type": "file",
        "format": "",
        "path": "/usr/lib/python2.7/httplib.py",
        "name": "",
        "version": "",
        "arch": "",
        "cpe": "file:/ec20a4287fb780da10392fc732c387076c348b4b",
        "licenses": null,
        "hash": "sha1:ec20a4287fb780da10392fc732c387076c348b4b"
      },
      "name": "CVE-2019-9947",
      "description": "An issue was discovered in urllib2 in Python 2.x through 2.7.16 and urllib in Python 3.x through 3.7.3. CRLF injection is possible if the attacker controls a url parameter, as demonstrated by the first argument to urllib.request.urlopen with \\r\\n (specifically in the path component of a URL that lacks a ? character) followed by an HTTP header or a Redis command. This is similar to the CVE-2019-9740 query string issue.",
      "publish_date": "2019-03-23",
      "modification_date": "2019-05-28",
      "vendor_severity": "medium",
      "vendor_cvss2_score": 6.1,
      "vendor_cvss2_vectors": "",
      "vendor_statement": "",
      "vendor_url": "https://bugs.python.org/issue35906",
      "nvd_severity": "medium",
      "nvd_cvss2_score": 4.3,
      "nvd_cvss2_vectors": "AV:N/AC:M/Au:N/C:N/I:P/A:N",
      "nvd_cvss3_severity": "medium",
      "nvd_cvss3_score": 6.1,
      "nvd_cvss3_vectors": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
      "nvd_url": "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2019-9947",
      "fix_version": "2.7.172.7, 3.5.73.5, 3.6.93.6, 3.7.43.7",
      "solution": "All Python 2.7.x users should upgrade to the latest version >= python-2.7.172.7\nAll Python 3.5.x users should upgrade to the latest version >= python-3.5.73.5/3.5m\nAll Python 3.6.x users should upgrade to the latest version >= python-3.6.93.6/3.6m\nAll Python 3.7x users should upgrade to the latest version >= python-3.7.43.7/3.7m\n\n3.7.4",
      "classification": "",
      "qualys_ids": null,
      "aqua_score": 6.1,
      "aqua_severity": "medium",
      "aqua_vectors": "",
      "aqua_scoring_system": "CVSS V2",
      "first_found_date": "2020-04-29",
      "last_found_date": "2020-04-29",
      "ancestor_pkg": "",
      "sibling_pkg": "",
      "v_patch_applied_by": "",
      "v_patch_applied_on": "",
      "v_patch_reverted_by": "",
      "v_patch_reverted_on": "",
      "v_patch_enforced_by": "",
      "v_patch_enforced_on": "",
      "v_patch_status": "patch_available",
      "acknowledged_date": "1970-01-01T00:00:00Z",
      "ack_scope": "",
      "ack_comment": "",
      "ack_author": "",
      "ack_expiration_days": 0,
      "ack_expiration_configured_at": "1970-01-01T00:00:00Z",
      "ack_expiration_configured_by": "",
      "v_patch_policy_name": "",
      "v_patch_policy_enforce": false,
      "audit_events_count": 0,
      "block_events_count": 0,
      "image_workload_info": null,
      "base_image_vulnerability": false,
      "base_image_name": ""
    },
    {
      "registry": "Host Images",
      "image_repository_name": "gcr.io/google-containers/hyperkube",
      "image_name": "gcr.io/google-containers/hyperkube:v1.16.6",
      "image_digest": "sha256:ae6fea104d3daa8321f9ba27767b3f8f25eefc37d6cbfea7a611da15cacae153",
      "referenced_vulnerabilities": null,
      "resource": {
        "type": "file",
        "format": "",
        "path": "/usr/lib/python2.7/urllib2.py",
        "name": "",
        "version": "",
        "arch": "",
        "cpe": "file:/39518b91529fcf5446868d97f9037db6da61fe13",
        "licenses": null,
        "hash": "sha1:39518b91529fcf5446868d97f9037db6da61fe13"
      },
      "name": "CVE-2019-9740",
      "description": "An issue was discovered in urllib2 in Python 2.x through 2.7.16 and urllib in Python 3.x through 3.7.3. CRLF injection is possible if the attacker controls a url parameter, as demonstrated by the first argument to urllib.request.urlopen with \\r\\n (specifically in the query string after a ? character) followed by an HTTP header or a Redis command.",
      "publish_date": "2019-03-13",
      "modification_date": "2019-05-28",
      "vendor_severity": "medium",
      "vendor_cvss2_score": 6.1,
      "vendor_cvss2_vectors": "",
      "vendor_statement": "",
      "vendor_url": "http://www.securityfocus.com/bid/107466",
      "nvd_severity": "medium",
      "nvd_cvss2_score": 4.3,
      "nvd_cvss2_vectors": "AV:N/AC:M/Au:N/C:N/I:P/A:N",
      "nvd_cvss3_severity": "medium",
      "nvd_cvss3_score": 6.1,
      "nvd_cvss3_vectors": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
      "nvd_url": "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2019-9740",
      "fix_version": "2.7.172.7, 3.5.73.5, 3.6.93.6, 3.7.43.7",
      "solution": "3.7.4\nAll Python 2.7.x users should upgrade to the latest version >= python-2.7.172.7\nAll Python 3.5.x users should upgrade to the latest version >= python-3.5.73.5/3.5m\nAll Python 3.6.x users should upgrade to the latest version >= python-3.6.93.6/3.6m\nAll Python 3.7x users should upgrade to the latest version >= python-3.7.43.7/3.7m",
      "classification": "",
      "qualys_ids": null,
      "aqua_score": 6.1,
      "aqua_severity": "medium",
      "aqua_vectors": "",
      "aqua_scoring_system": "CVSS V2",
      "first_found_date": "2020-04-29",
      "last_found_date": "2020-04-29",
      "ancestor_pkg": "",
      "sibling_pkg": "",
      "v_patch_applied_by": "",
      "v_patch_applied_on": "",
      "v_patch_reverted_by": "",
      "v_patch_reverted_on": "",
      "v_patch_enforced_by": "",
      "v_patch_enforced_on": "",
      "v_patch_status": "patch_available",
      "acknowledged_date": "1970-01-01T00:00:00Z",
      "ack_scope": "",
      "ack_comment": "",
      "ack_author": "",
      "ack_expiration_days": 0,
      "ack_expiration_configured_at": "1970-01-01T00:00:00Z",
      "ack_expiration_configured_by": "",
      "v_patch_policy_name": "",
      "v_patch_policy_enforce": false,
      "audit_events_count": 0,
      "block_events_count": 0,
      "image_workload_info": null,
      "base_image_vulnerability": false,
      "base_image_name": ""
    },
    {
      "registry": "Host Images",
      "image_repository_name": "registry.aquasec.com/enforcer",
      "image_name": "registry.aquasec.com/enforcer:4.6",
      "image_digest": "sha256:39931a1c9fd34dbfab0d51bf20992c3b70228d3142056840024219eaccd1e160",
      "referenced_vulnerabilities": null,
      "resource": {
        "type": "package",
        "format": "apk",
        "path": "",
        "name": "libssh2",
        "version": "1.9.0-r1",
        "arch": "x86_64",
        "cpe": "pkg:/alpine:3.7.3:libssh2:1.9.0-r1",
        "licenses": [
          "BSD"
        ],
        "hash": ""
      },
      "name": "CVE-2019-17498",
      "description": "In libssh2 v1.9.0 and earlier versions, the SSH_MSG_DISCONNECT logic in packet.c has an integer overflow in a bounds check, enabling an attacker to specify an arbitrary (out-of-bounds) offset for a subsequent memory read. A crafted SSH server may be able to disclose sensitive information or cause a denial of service condition on the client system when a user connects to the server.",
      "publish_date": "2019-10-21",
      "modification_date": "2019-11-07",
      "vendor_severity": "medium",
      "vendor_cvss2_score": 5.8,
      "vendor_cvss2_vectors": "AV:N/AC:M/Au:N/C:P/I:N/A:P",
      "vendor_statement": "",
      "vendor_url": "",
      "nvd_severity": "medium",
      "nvd_cvss2_score": 5.8,
      "nvd_cvss2_vectors": "AV:N/AC:M/Au:N/C:P/I:N/A:P",
      "nvd_cvss3_severity": "high",
      "nvd_cvss3_score": 8.1,
      "nvd_cvss3_vectors": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:N/A:H",
      "nvd_url": "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2019-17498",
      "fix_version": "",
      "solution": "",
      "classification": "",
      "qualys_ids": null,
      "aqua_score": 5.8,
      "aqua_severity": "medium",
      "aqua_vectors": "AV:N/AC:M/Au:N/C:P/I:N/A:P",
      "aqua_scoring_system": "CVSS V2",
      "first_found_date": "2020-04-29",
      "last_found_date": "2020-04-29",
      "ancestor_pkg": "",
      "sibling_pkg": "",
      "v_patch_applied_by": "",
      "v_patch_applied_on": "",
      "v_patch_reverted_by": "",
      "v_patch_reverted_on": "",
      "v_patch_enforced_by": "",
      "v_patch_enforced_on": "",
      "v_patch_status": "no_patch",
      "acknowledged_date": "1970-01-01T00:00:00Z",
      "ack_scope": "",
      "ack_comment": "",
      "ack_author": "",
      "ack_expiration_days": 0,
      "ack_expiration_configured_at": "1970-01-01T00:00:00Z",
      "ack_expiration_configured_by": "",
      "v_patch_policy_name": "",
      "v_patch_policy_enforce": false,
      "audit_events_count": 0,
      "block_events_count": 0,
      "image_workload_info": null,
      "base_image_vulnerability": false,
      "base_image_name": ""
    },
    {
      "registry": "Host Images",
      "image_repository_name": "digitalocean/do-csi-plugin",
      "image_name": "digitalocean/do-csi-plugin:v1.2.0",
      "image_digest": "sha256:84fa1763b48ad0a348676fa3bb893e759eb153febf399876af8926879d401fb1",
      "referenced_vulnerabilities": null,
      "resource": {
        "type": "package",
        "format": "apk",
        "path": "",
        "name": "busybox",
        "version": "1.27.2-r11",
        "arch": "x86_64",
        "cpe": "pkg:/alpine:3.7.3:busybox:1.27.2-r11",
        "licenses": [
          "GPL2"
        ],
        "hash": ""
      },
      "name": "CVE-2018-20679",
      "description": "An issue was discovered in BusyBox before 1.30.0. An out of bounds read in udhcp components (consumed by the DHCP server, client, and relay) allows a remote attacker to leak sensitive information from the stack by sending a crafted DHCP message. This is related to verification in udhcp_get_option() in networking/udhcp/common.c that 4-byte options are indeed 4 bytes.",
      "publish_date": "2019-01-09",
      "modification_date": "2019-09-04",
      "vendor_severity": "medium",
      "vendor_cvss2_score": 5,
      "vendor_cvss2_vectors": "AV:N/AC:L/Au:N/C:P/I:N/A:N",
      "vendor_statement": "",
      "vendor_url": "",
      "nvd_severity": "medium",
      "nvd_cvss2_score": 5,
      "nvd_cvss2_vectors": "AV:N/AC:L/Au:N/C:P/I:N/A:N",
      "nvd_cvss3_severity": "high",
      "nvd_cvss3_score": 7.5,
      "nvd_cvss3_vectors": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
      "nvd_url": "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2018-20679",
      "fix_version": "",
      "solution": "",
      "classification": "",
      "qualys_ids": null,
      "aqua_score": 5,
      "aqua_severity": "medium",
      "aqua_vectors": "AV:N/AC:L/Au:N/C:P/I:N/A:N",
      "aqua_scoring_system": "CVSS V2",
      "first_found_date": "2020-04-29",
      "last_found_date": "2020-04-29",
      "ancestor_pkg": "",
      "sibling_pkg": "",
      "v_patch_applied_by": "",
      "v_patch_applied_on": "",
      "v_patch_reverted_by": "",
      "v_patch_reverted_on": "",
      "v_patch_enforced_by": "",
      "v_patch_enforced_on": "",
      "v_patch_status": "no_patch",
      "acknowledged_date": "1970-01-01T00:00:00Z",
      "ack_scope": "",
      "ack_comment": "",
      "ack_author": "",
      "ack_expiration_days": 0,
      "ack_expiration_configured_at": "1970-01-01T00:00:00Z",
      "ack_expiration_configured_by": "",
      "v_patch_policy_name": "",
      "v_patch_policy_enforce": false,
      "audit_events_count": 0,
      "block_events_count": 0,
      "image_workload_info": null,
      "base_image_vulnerability": false,
      "base_image_name": ""
    },
    {
      "registry": "Host Images",
      "image_repository_name": "digitalocean/do-csi-plugin",
      "image_name": "digitalocean/do-csi-plugin:v1.2.0",
      "image_digest": "sha256:84fa1763b48ad0a348676fa3bb893e759eb153febf399876af8926879d401fb1",
      "referenced_vulnerabilities": null,
      "resource": {
        "type": "package",
        "format": "apk",
        "path": "",
        "name": "busybox",
        "version": "1.27.2-r11",
        "arch": "x86_64",
        "cpe": "pkg:/alpine:3.7.3:busybox:1.27.2-r11",
        "licenses": [
          "GPL2"
        ],
        "hash": ""
      },
      "name": "CVE-2019-5747",
      "description": "An issue was discovered in BusyBox through 1.30.0. An out of bounds read in udhcp components (consumed by the DHCP server, client, and/or relay) might allow a remote attacker to leak sensitive information from the stack by sending a crafted DHCP message. This is related to assurance of a 4-byte length when decoding DHCP_SUBNET. NOTE: this issue exists because of an incomplete fix for CVE-2018-20679.",
      "publish_date": "2019-01-09",
      "modification_date": "2019-09-04",
      "vendor_severity": "medium",
      "vendor_cvss2_score": 5,
      "vendor_cvss2_vectors": "AV:N/AC:L/Au:N/C:P/I:N/A:N",
      "vendor_statement": "",
      "vendor_url": "",
      "nvd_severity": "medium",
      "nvd_cvss2_score": 5,
      "nvd_cvss2_vectors": "AV:N/AC:L/Au:N/C:P/I:N/A:N",
      "nvd_cvss3_severity": "high",
      "nvd_cvss3_score": 7.5,
      "nvd_cvss3_vectors": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
      "nvd_url": "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2019-5747",
      "fix_version": "",
      "solution": "",
      "classification": "",
      "qualys_ids": null,
      "aqua_score": 5,
      "aqua_severity": "medium",
      "aqua_vectors": "AV:N/AC:L/Au:N/C:P/I:N/A:N",
      "aqua_scoring_system": "CVSS V2",
      "first_found_date": "2020-04-29",
      "last_found_date": "2020-04-29",
      "ancestor_pkg": "",
      "sibling_pkg": "",
      "v_patch_applied_by": "",
      "v_patch_applied_on": "",
      "v_patch_reverted_by": "",
      "v_patch_reverted_on": "",
      "v_patch_enforced_by": "",
      "v_patch_enforced_on": "",
      "v_patch_status": "no_patch",
      "acknowledged_date": "1970-01-01T00:00:00Z",
      "ack_scope": "",
      "ack_comment": "",
      "ack_author": "",
      "ack_expiration_days": 0,
      "ack_expiration_configured_at": "1970-01-01T00:00:00Z",
      "ack_expiration_configured_by": "",
      "v_patch_policy_name": "",
      "v_patch_policy_enforce": false,
      "audit_events_count": 0,
      "block_events_count": 0,
      "image_workload_info": null,
      "base_image_vulnerability": false,
      "base_image_name": ""
    },
    {
      "registry": "Host Images",
      "image_repository_name": "quay.io/kubernetes-ingress-controller/nginx-ingress-controller",
      "image_name": "quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.26.1",
      "image_digest": "sha256:29024c9c6e706357bebda26ea9a15064e77616f4d40c215ce81ae5e4b2a460aa",
      "referenced_vulnerabilities": null,
      "resource": {
        "type": "package",
        "format": "deb",
        "path": "",
        "name": "openssl",
        "version": "1.1.1c-1",
        "arch": "amd64",
        "cpe": "pkg:/debian:10:openssl:1.1.1c-1",
        "licenses": null,
        "hash": ""
      },
      "name": "CVE-2019-1549",
      "description": "OpenSSL 1.1.1 introduced a rewritten random number generator (RNG). This was intended to include protection in the event of a fork() system call in order to ensure that the parent and child processes did not share the same RNG state. However this protection was not being used in the default case. A partial mitigation for this issue is that the output from a high precision timer is mixed into the RNG state so the likelihood of a parent and child process sharing state is significantly reduced. If an application already calls OPENSSL_init_crypto() explicitly using OPENSSL_INIT_ATFORK then this problem does not occur at all. Fixed in OpenSSL 1.1.1d (Affected 1.1.1-1.1.1c).",
      "publish_date": "2019-09-10",
      "modification_date": "2019-09-19",
      "vendor_severity": "medium",
      "vendor_cvss2_score": 5,
      "vendor_cvss2_vectors": "AV:N/AC:L/Au:N/C:P/I:N/A:N",
      "vendor_statement": "https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=1b0fe00e2704b5e20334a16d3c9099d1ba2ef1be\nhttps://www.openssl.org/news/secadv/20190910.txt",
      "vendor_url": "https://security-tracker.debian.org/tracker/CVE-2019-1549",
      "nvd_severity": "medium",
      "nvd_cvss2_score": 5,
      "nvd_cvss2_vectors": "AV:N/AC:L/Au:N/C:P/I:N/A:N",
      "nvd_cvss3_severity": "medium",
      "nvd_cvss3_score": 5.3,
      "nvd_cvss3_vectors": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N",
      "nvd_url": "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2019-1549",
      "fix_version": "1.1.1d-0+deb10u1",
      "solution": "Upgrade package openssl to version 1.1.1d-0+deb10u1 or above.",
      "classification": "",
      "qualys_ids": null,
      "aqua_score": 5,
      "aqua_severity": "medium",
      "aqua_vectors": "AV:N/AC:L/Au:N/C:P/I:N/A:N",
      "aqua_scoring_system": "CVSS V2",
      "first_found_date": "2020-04-29",
      "last_found_date": "2020-04-29",
      "ancestor_pkg": "",
      "sibling_pkg": "",
      "v_patch_applied_by": "",
      "v_patch_applied_on": "",
      "v_patch_reverted_by": "",
      "v_patch_reverted_on": "",
      "v_patch_enforced_by": "",
      "v_patch_enforced_on": "",
      "v_patch_status": "patch_available",
      "acknowledged_date": "1970-01-01T00:00:00Z",
      "ack_scope": "",
      "ack_comment": "",
      "ack_author": "",
      "ack_expiration_days": 0,
      "ack_expiration_configured_at": "1970-01-01T00:00:00Z",
      "ack_expiration_configured_by": "",
      "v_patch_policy_name": "",
      "v_patch_policy_enforce": false,
      "audit_events_count": 0,
      "block_events_count": 0,
      "image_workload_info": null,
      "base_image_vulnerability": false,
      "base_image_name": ""
    },
    {
      "registry": "Host Images",
      "image_repository_name": "gcr.io/google-containers/hyperkube",
      "image_name": "gcr.io/google-containers/hyperkube:v1.16.6",
      "image_digest": "sha256:ae6fea104d3daa8321f9ba27767b3f8f25eefc37d6cbfea7a611da15cacae153",
      "referenced_vulnerabilities": [
        {
          "registry": "",
          "image_repository_name": "",
          "referenced_vulnerabilities": null,
          "resource": {
            "type": "",
            "format": "",
            "path": "",
            "name": "",
            "version": "",
            "arch": "",
            "cpe": "",
            "licenses": null,
            "hash": ""
          },
          "name": "CVE-2020-5260",
          "description": "Affected versions of Git have a vulnerability whereby Git can be tricked into sending private credentials to a host controlled by an attacker. Git uses external \"credential helper\" programs to store and retrieve passwords or other credentials from secure storage provided by the operating system. Specially-crafted URLs that contain an encoded newline can inject unintended values into the credential helper protocol stream, causing the credential helper to retrieve the password for one server (e.g., good.example.com) for an HTTP request being made to another server (e.g., evil.example.com), resulting in credentials for the former being sent to the latter. There are no restrictions on the relationship between the two, meaning that an attacker can craft a URL that will present stored credentials for any host to a host of their choosing. The vulnerability can be triggered by feeding a malicious URL to git clone. However, the affected URLs look rather suspicious; the likely vector would be through systems which automatically clone URLs not visible to the user, such as Git submodules, or package systems built around Git. The problem has been patched in the versions published on April 14th, 2020, going back to v2.17.x. Anyone wishing to backport the change further can do so by applying commit 9a6bbee (the full release includes extra checks for git fsck, but that commit is sufficient to protect clients against the vulnerability). The patched versions are: 2.17.4, 2.18.3, 2.19.4, 2.20.3, 2.21.2, 2.22.3, 2.23.2, 2.24.2, 2.25.3, 2.26.1.",
          "publish_date": "2020-04-14",
          "modification_date": "2020-04-25",
          "vendor_severity": "medium",
          "vendor_cvss2_score": 5,
          "vendor_cvss2_vectors": "AV:N/AC:L/Au:N/C:P/I:N/A:N",
          "vendor_cvss3_severity": "high",
          "vendor_cvss3_score": 7.5,
          "vendor_cvss3_vectors": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
          "vendor_statement": "https://lore.kernel.org/lkml/xmqqy2qy7xn8.fsf@gitster.c.googlers.com/\nFixed by: https://git.kernel.org/pub/scm/git/git.git/commit/?id=9a6bbee8006c24b46a85d29e7b38cfa79e9ab21b\nAdditional/nice-to-have: https://git.kernel.org/pub/scm/git/git.git/commit/?id=17f1c0b8c7e447aa62f85dc355bb48133d2812f2\nAdditional/nice-to-have: https://git.kernel.org/pub/scm/git/git.git/commit/?id=c716fe4bd917e013bf376a678b3a924447777b2d\nAdditional/nice-to-have: https://git.kernel.org/pub/scm/git/git.git/commit/?id=07259e74ec1237c836874342c65650bdee8a3993\nhttps://bugs.chromium.org/p/project-zero/issues/detail?id=2021\nhttps://github.com/git/git/security/advisories/GHSA-qm7j-c969-7j4q",
          "vendor_url": "https://security-tracker.debian.org/tracker/CVE-2020-5260",
          "nvd_severity": "medium",
          "nvd_cvss2_score": 5,
          "nvd_cvss2_vectors": "AV:N/AC:L/Au:N/C:P/I:N/A:N",
          "nvd_cvss3_severity": "high",
          "nvd_cvss3_score": 7.5,
          "nvd_cvss3_vectors": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
          "nvd_url": "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2020-5260",
          "fix_version": "",
          "solution": "",
          "classification": "",
          "qualys_ids": null,
          "aqua_score": 5,
          "aqua_severity": "medium",
          "aqua_vectors": "AV:N/AC:L/Au:N/C:P/I:N/A:N",
          "aqua_scoring_system": "CVSS V2",
          "first_found_date": "2020-04-29",
          "last_found_date": "2020-04-29",
          "ancestor_pkg": "",
          "sibling_pkg": "",
          "v_patch_applied_by": "",
          "v_patch_applied_on": "",
          "v_patch_reverted_by": "",
          "v_patch_reverted_on": "",
          "v_patch_enforced_by": "",
          "v_patch_enforced_on": "",
          "v_patch_status": "",
          "acknowledged_date": "0001-01-01T00:00:00Z",
          "ack_scope": "",
          "ack_comment": "",
          "ack_author": "",
          "ack_expiration_days": 0,
          "ack_expiration_configured_at": "0001-01-01T00:00:00Z",
          "ack_expiration_configured_by": "",
          "v_patch_policy_name": "",
          "v_patch_policy_enforce": false,
          "audit_events_count": 0,
          "block_events_count": 0,
          "image_workload_info": null,
          "base_image_vulnerability": false,
          "base_image_name": ""
        }
      ],
      "resource": {
        "type": "package",
        "format": "deb",
        "path": "",
        "name": "git",
        "version": "1:2.11.0-3+deb9u4",
        "arch": "amd64",
        "cpe": "pkg:/debian:9:git:1:2.11.0-3+deb9u4",
        "licenses": null,
        "hash": ""
      },
      "name": "DSA-4657-1",
      "description": "",
      "publish_date": "",
      "modification_date": "",
      "vendor_severity": "medium",
      "vendor_cvss2_score": 5,
      "vendor_cvss2_vectors": "AV:N/AC:L/Au:N/C:P/I:N/A:N",
      "vendor_statement": "",
      "vendor_url": "https://security-tracker.debian.org/tracker/DSA-4657-1",
      "nvd_severity": "medium",
      "nvd_cvss2_score": 5,
      "nvd_cvss2_vectors": "AV:N/AC:L/Au:N/C:P/I:N/A:N",
      "nvd_cvss3_severity": "high",
      "nvd_cvss3_score": 7.5,
      "nvd_cvss3_vectors": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
      "nvd_url": "",
      "fix_version": "1:2.11.0-3+deb9u6",
      "solution": "Upgrade package git to version 1:2.11.0-3+deb9u6 or above.",
      "classification": "",
      "qualys_ids": null,
      "aqua_score": 5,
      "aqua_severity": "medium",
      "aqua_vectors": "AV:N/AC:L/Au:N/C:P/I:N/A:N",
      "aqua_scoring_system": "CVSS V2",
      "first_found_date": "2020-04-29",
      "last_found_date": "2020-04-29",
      "ancestor_pkg": "",
      "sibling_pkg": "",
      "v_patch_applied_by": "",
      "v_patch_applied_on": "",
      "v_patch_reverted_by": "",
      "v_patch_reverted_on": "",
      "v_patch_enforced_by": "",
      "v_patch_enforced_on": "",
      "v_patch_status": "no_patch",
      "acknowledged_date": "1970-01-01T00:00:00Z",
      "ack_scope": "",
      "ack_comment": "",
      "ack_author": "",
      "ack_expiration_days": 0,
      "ack_expiration_configured_at": "1970-01-01T00:00:00Z",
      "ack_expiration_configured_by": "",
      "v_patch_policy_name": "",
      "v_patch_policy_enforce": false,
      "audit_events_count": 0,
      "block_events_count": 0,
      "image_workload_info": null,
      "base_image_vulnerability": false,
      "base_image_name": ""
    },
    {
      "registry": "Host Images",
      "image_repository_name": "cilium/cilium",
      "image_name": "cilium/cilium:v1.6.4",
      "image_digest": "sha256:bb03d78998ace9cbb018e0f911a2b62d8228800b03e75eac226f11203c18fd7d",
      "referenced_vulnerabilities": null,
      "resource": {
        "type": "package",
        "format": "deb",
        "path": "",
        "name": "binutils",
        "version": "2.30-21ubuntu1~18.04.2",
        "arch": "amd64",
        "cpe": "pkg:/ubuntu:18.04:binutils:2.30-21ubuntu1~18.04.2",
        "licenses": null,
        "hash": ""
      },
      "name": "CVE-2019-14444",
      "description": "apply_relocations in readelf.c in GNU Binutils 2.32 contains an integer overflow that allows attackers to trigger a write access violation (in byte_put_little_endian function in elfcomm.c) via an ELF file, as demonstrated by readelf.",
      "publish_date": "2019-07-30",
      "modification_date": "2019-08-22",
      "vendor_severity": "medium",
      "vendor_cvss2_score": 5,
      "vendor_cvss2_vectors": "",
      "vendor_statement": "",
      "vendor_url": "https://people.canonical.com/~ubuntu-security/cve/2019/CVE-2019-14444.html",
      "nvd_severity": "medium",
      "nvd_cvss2_score": 4.3,
      "nvd_cvss2_vectors": "AV:N/AC:M/Au:N/C:N/I:N/A:P",
      "nvd_cvss3_severity": "medium",
      "nvd_cvss3_score": 5.5,
      "nvd_cvss3_vectors": "CVSS:3.0/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
      "nvd_url": "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2019-14444",
      "fix_version": "2.30-21ubuntu1~18.04.3",
      "solution": "Upgrade package binutils to version 2.30-21ubuntu1~18.04.3 or above.",
      "classification": "",
      "qualys_ids": null,
      "aqua_score": 5,
      "aqua_severity": "medium",
      "aqua_vectors": "",
      "aqua_scoring_system": "CVSS V2",
      "first_found_date": "2020-04-29",
      "last_found_date": "2020-04-29",
      "ancestor_pkg": "",
      "sibling_pkg": "",
      "v_patch_applied_by": "",
      "v_patch_applied_on": "",
      "v_patch_reverted_by": "",
      "v_patch_reverted_on": "",
      "v_patch_enforced_by": "",
      "v_patch_enforced_on": "",
      "v_patch_status": "patch_available",
      "acknowledged_date": "1970-01-01T00:00:00Z",
      "ack_scope": "",
      "ack_comment": "",
      "ack_author": "",
      "ack_expiration_days": 0,
      "ack_expiration_configured_at": "1970-01-01T00:00:00Z",
      "ack_expiration_configured_by": "",
      "v_patch_policy_name": "",
      "v_patch_policy_enforce": false,
      "audit_events_count": 0,
      "block_events_count": 0,
      "image_workload_info": null,
      "base_image_vulnerability": false,
      "base_image_name": ""
    },
    {
      "registry": "Host Images",
      "image_repository_name": "cilium/cilium",
      "image_name": "cilium/cilium:v1.6.4",
      "image_digest": "sha256:bb03d78998ace9cbb018e0f911a2b62d8228800b03e75eac226f11203c18fd7d",
      "referenced_vulnerabilities": null,
      "resource": {
        "type": "package",
        "format": "deb",
        "path": "",
        "name": "binutils",
        "version": "2.30-21ubuntu1~18.04.2",
        "arch": "amd64",
        "cpe": "pkg:/ubuntu:18.04:binutils:2.30-21ubuntu1~18.04.2",
        "licenses": null,
        "hash": ""
      },
      "name": "CVE-2019-14250",
      "description": "An issue was discovered in GNU libiberty, as distributed in GNU Binutils 2.32. simple_object_elf_match in simple-object-elf.c does not check for a zero shstrndx value, leading to an integer overflow and resultant heap-based buffer overflow.",
      "publish_date": "2019-07-24",
      "modification_date": "2019-08-22",
      "vendor_severity": "medium",
      "vendor_cvss2_score": 5,
      "vendor_cvss2_vectors": "",
      "vendor_statement": "",
      "vendor_url": "https://people.canonical.com/~ubuntu-security/cve/2019/CVE-2019-14250.html",
      "nvd_severity": "medium",
      "nvd_cvss2_score": 4.3,
      "nvd_cvss2_vectors": "AV:N/AC:M/Au:N/C:N/I:N/A:P",
      "nvd_cvss3_severity": "medium",
      "nvd_cvss3_score": 5.5,
      "nvd_cvss3_vectors": "CVSS:3.0/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:N/A:N",
      "nvd_url": "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2019-14250",
      "fix_version": "2.30-21ubuntu1~18.04.3",
      "solution": "Upgrade package binutils to version 2.30-21ubuntu1~18.04.3 or above.",
      "classification": "",
      "qualys_ids": null,
      "aqua_score": 5,
      "aqua_severity": "medium",
      "aqua_vectors": "",
      "aqua_scoring_system": "CVSS V2",
      "first_found_date": "2020-04-29",
      "last_found_date": "2020-04-29",
      "ancestor_pkg": "",
      "sibling_pkg": "",
      "v_patch_applied_by": "",
      "v_patch_applied_on": "",
      "v_patch_reverted_by": "",
      "v_patch_reverted_on": "",
      "v_patch_enforced_by": "",
      "v_patch_enforced_on": "",
      "v_patch_status": "patch_available",
      "acknowledged_date": "1970-01-01T00:00:00Z",
      "ack_scope": "",
      "ack_comment": "",
      "ack_author": "",
      "ack_expiration_days": 0,
      "ack_expiration_configured_at": "1970-01-01T00:00:00Z",
      "ack_expiration_configured_by": "",
      "v_patch_policy_name": "",
      "v_patch_policy_enforce": false,
      "audit_events_count": 0,
      "block_events_count": 0,
      "image_workload_info": null,
      "base_image_vulnerability": false,
      "base_image_name": ""
    },
    {
      "registry": "Host Images",
      "image_repository_name": "cilium/cilium",
      "image_name": "cilium/cilium:v1.6.4",
      "image_digest": "sha256:bb03d78998ace9cbb018e0f911a2b62d8228800b03e75eac226f11203c18fd7d",
      "referenced_vulnerabilities": null,
      "resource": {
        "type": "package",
        "format": "deb",
        "path": "",
        "name": "binutils",
        "version": "2.30-21ubuntu1~18.04.2",
        "arch": "amd64",
        "cpe": "pkg:/ubuntu:18.04:binutils:2.30-21ubuntu1~18.04.2",
        "licenses": null,
        "hash": ""
      },
      "name": "CVE-2019-17451",
      "description": "An issue was discovered in the Binary File Descriptor (BFD) library (aka libbfd), as distributed in GNU Binutils 2.32. It is an integer overflow leading to a SEGV in _bfd_dwarf2_find_nearest_line in dwarf2.c, as demonstrated by nm.",
      "publish_date": "2019-10-10",
      "modification_date": "2019-10-24",
      "vendor_severity": "medium",
      "vendor_cvss2_score": 5,
      "vendor_cvss2_vectors": "",
      "vendor_statement": "",
      "vendor_url": "https://people.canonical.com/~ubuntu-security/cve/2019/CVE-2019-17451.html",
      "nvd_severity": "medium",
      "nvd_cvss2_score": 4.3,
      "nvd_cvss2_vectors": "AV:N/AC:M/Au:N/C:N/I:N/A:P",
      "nvd_cvss3_severity": "medium",
      "nvd_cvss3_score": 6.5,
      "nvd_cvss3_vectors": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
      "nvd_url": "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2019-17451",
      "fix_version": "2.30-21ubuntu1~18.04.3",
      "solution": "Upgrade package binutils to version 2.30-21ubuntu1~18.04.3 or above.",
      "classification": "",
      "qualys_ids": null,
      "aqua_score": 5,
      "aqua_severity": "medium",
      "aqua_vectors": "",
      "aqua_scoring_system": "CVSS V2",
      "first_found_date": "2020-04-29",
      "last_found_date": "2020-04-29",
      "ancestor_pkg": "",
      "sibling_pkg": "",
      "v_patch_applied_by": "",
      "v_patch_applied_on": "",
      "v_patch_reverted_by": "",
      "v_patch_reverted_on": "",
      "v_patch_enforced_by": "",
      "v_patch_enforced_on": "",
      "v_patch_status": "patch_available",
      "acknowledged_date": "1970-01-01T00:00:00Z",
      "ack_scope": "",
      "ack_comment": "",
      "ack_author": "",
      "ack_expiration_days": 0,
      "ack_expiration_configured_at": "1970-01-01T00:00:00Z",
      "ack_expiration_configured_by": "",
      "v_patch_policy_name": "",
      "v_patch_policy_enforce": false,
      "audit_events_count": 0,
      "block_events_count": 0,
      "image_workload_info": null,
      "base_image_vulnerability": false,
      "base_image_name": ""
    },
    {
      "registry": "Host Images",
      "image_repository_name": "cilium/cilium",
      "image_name": "cilium/cilium:v1.6.4",
      "image_digest": "sha256:bb03d78998ace9cbb018e0f911a2b62d8228800b03e75eac226f11203c18fd7d",
      "referenced_vulnerabilities": null,
      "resource": {
        "type": "package",
        "format": "deb",
        "path": "",
        "name": "e2fsprogs",
        "version": "1.44.1-1ubuntu1.2",
        "arch": "amd64",
        "cpe": "pkg:/ubuntu:18.04:e2fsprogs:1.44.1-1ubuntu1.2",
        "licenses": null,
        "hash": ""
      },
      "name": "CVE-2019-5188",
      "description": "A code execution vulnerability exists in the directory rehashing functionality of E2fsprogs e2fsck 1.45.4. A specially crafted ext4 directory can cause an out-of-bounds write on the stack, resulting in code execution. An attacker can corrupt a partition to trigger this vulnerability.",
      "publish_date": "2020-01-08",
      "modification_date": "2020-01-28",
      "vendor_severity": "medium",
      "vendor_cvss2_score": 5,
      "vendor_cvss2_vectors": "",
      "vendor_statement": "",
      "vendor_url": "https://people.canonical.com/~ubuntu-security/cve/2019/CVE-2019-5188.html",
      "nvd_severity": "medium",
      "nvd_cvss2_score": 4.6,
      "nvd_cvss2_vectors": "AV:L/AC:L/Au:N/C:P/I:P/A:P",
      "nvd_cvss3_severity": "medium",
      "nvd_cvss3_score": 6.7,
      "nvd_cvss3_vectors": "CVSS:3.1/AV:L/AC:L/PR:H/UI:N/S:U/C:H/I:H/A:H",
      "nvd_url": "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2019-5188",
      "fix_version": "1.44.1-1ubuntu1.3",
      "solution": "Upgrade package e2fsprogs to version 1.44.1-1ubuntu1.3 or above.",
      "classification": "",
      "qualys_ids": null,
      "aqua_score": 5,
      "aqua_severity": "medium",
      "aqua_vectors": "",
      "aqua_scoring_system": "CVSS V2",
      "first_found_date": "2020-04-29",
      "last_found_date": "2020-04-29",
      "ancestor_pkg": "",
      "sibling_pkg": "",
      "v_patch_applied_by": "",
      "v_patch_applied_on": "",
      "v_patch_reverted_by": "",
      "v_patch_reverted_on": "",
      "v_patch_enforced_by": "",
      "v_patch_enforced_on": "",
      "v_patch_status": "patch_available",
      "acknowledged_date": "1970-01-01T00:00:00Z",
      "ack_scope": "",
      "ack_comment": "",
      "ack_author": "",
      "ack_expiration_days": 0,
      "ack_expiration_configured_at": "1970-01-01T00:00:00Z",
      "ack_expiration_configured_by": "",
      "v_patch_policy_name": "",
      "v_patch_policy_enforce": false,
      "audit_events_count": 0,
      "block_events_count": 0,
      "image_workload_info": null,
      "base_image_vulnerability": false,
      "base_image_name": ""
    },
    {
      "registry": "Host Images",
      "image_repository_name": "cilium/cilium",
      "image_name": "cilium/cilium:v1.6.4",
      "image_digest": "sha256:bb03d78998ace9cbb018e0f911a2b62d8228800b03e75eac226f11203c18fd7d",
      "referenced_vulnerabilities": null,
      "resource": {
        "type": "package",
        "format": "deb",
        "path": "",
        "name": "libgcrypt20",
        "version": "1.8.1-4ubuntu1.1",
        "arch": "amd64",
        "cpe": "pkg:/ubuntu:18.04:libgcrypt20:1.8.1-4ubuntu1.1",
        "licenses": null,
        "hash": ""
      },
      "name": "CVE-2019-13627",
      "description": "It was discovered that there was a ECDSA timing attack in the libgcrypt20 cryptographic library. Version affected: 1.8.4-5, 1.7.6-2+deb9u3, and 1.6.3-2+deb8u4. Versions fixed: 1.8.5-2 and 1.6.3-2+deb8u7.",
      "publish_date": "2019-09-25",
      "modification_date": "2020-04-01",
      "vendor_severity": "medium",
      "vendor_cvss2_score": 5,
      "vendor_cvss2_vectors": "",
      "vendor_statement": "",
      "vendor_url": "https://people.canonical.com/~ubuntu-security/cve/2019/CVE-2019-13627.html",
      "nvd_severity": "low",
      "nvd_cvss2_score": 2.6,
      "nvd_cvss2_vectors": "AV:L/AC:H/Au:N/C:P/I:P/A:N",
      "nvd_cvss3_severity": "medium",
      "nvd_cvss3_score": 6.3,
      "nvd_cvss3_vectors": "CVSS:3.1/AV:L/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:N",
      "nvd_url": "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2019-13627",
      "fix_version": "1.8.1-4ubuntu1.2",
      "solution": "Upgrade package libgcrypt20 to version 1.8.1-4ubuntu1.2 or above.",
      "classification": "",
      "qualys_ids": null,
      "aqua_score": 5,
      "aqua_severity": "medium",
      "aqua_vectors": "",
      "aqua_scoring_system": "CVSS V2",
      "first_found_date": "2020-04-29",
      "last_found_date": "2020-04-29",
      "ancestor_pkg": "",
      "sibling_pkg": "",
      "v_patch_applied_by": "",
      "v_patch_applied_on": "",
      "v_patch_reverted_by": "",
      "v_patch_reverted_on": "",
      "v_patch_enforced_by": "",
      "v_patch_enforced_on": "",
      "v_patch_status": "patch_available",
      "acknowledged_date": "1970-01-01T00:00:00Z",
      "ack_scope": "",
      "ack_comment": "",
      "ack_author": "",
      "ack_expiration_days": 0,
      "ack_expiration_configured_at": "1970-01-01T00:00:00Z",
      "ack_expiration_configured_by": "",
      "v_patch_policy_name": "",
      "v_patch_policy_enforce": false,
      "audit_events_count": 0,
      "block_events_count": 0,
      "image_workload_info": null,
      "base_image_vulnerability": false,
      "base_image_name": ""
    },
    {
      "registry": "Host Images",
      "image_repository_name": "gcr.io/google-containers/hyperkube",
      "image_name": "gcr.io/google-containers/hyperkube:v1.16.6",
      "image_digest": "sha256:ae6fea104d3daa8321f9ba27767b3f8f25eefc37d6cbfea7a611da15cacae153",
      "referenced_vulnerabilities": [
        {
          "registry": "",
          "image_repository_name": "",
          "referenced_vulnerabilities": null,
          "resource": {
            "type": "",
            "format": "",
            "path": "",
            "name": "",
            "version": "",
            "arch": "",
            "cpe": "",
            "licenses": null,
            "hash": ""
          },
          "name": "CVE-2019-5094",
          "description": "An exploitable code execution vulnerability exists in the quota file functionality of E2fsprogs 1.45.3. A specially crafted ext4 partition can cause an out-of-bounds write on the heap, resulting in code execution. An attacker can corrupt a partition to trigger this vulnerability.",
          "publish_date": "2019-09-24",
          "modification_date": "2019-09-28",
          "vendor_severity": "medium",
          "vendor_cvss2_score": 4.6,
          "vendor_cvss2_vectors": "AV:L/AC:L/Au:N/C:P/I:P/A:P",
          "vendor_cvss3_severity": "medium",
          "vendor_cvss3_score": 6.7,
          "vendor_cvss3_vectors": "CVSS:3.1/AV:L/AC:L/PR:H/UI:N/S:U/C:H/I:H/A:H",
          "vendor_statement": "https://git.kernel.org/pub/scm/fs/ext2/e2fsprogs.git/commit/?h=maint&id=8dbe7b475ec5e91ed767239f0e85880f416fc384\nhttps://talosintelligence.com/vulnerability_reports/TALOS-2019-0887",
          "vendor_url": "https://security-tracker.debian.org/tracker/CVE-2019-5094",
          "nvd_severity": "medium",
          "nvd_cvss2_score": 4.6,
          "nvd_cvss2_vectors": "AV:L/AC:L/Au:N/C:P/I:P/A:P",
          "nvd_cvss3_severity": "medium",
          "nvd_cvss3_score": 6.7,
          "nvd_cvss3_vectors": "CVSS:3.1/AV:L/AC:L/PR:H/UI:N/S:U/C:H/I:H/A:H",
          "nvd_url": "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2019-5094",
          "fix_version": "",
          "solution": "",
          "classification": "",
          "qualys_ids": null,
          "aqua_score": 4.6,
          "aqua_severity": "medium",
          "aqua_vectors": "AV:L/AC:L/Au:N/C:P/I:P/A:P",
          "aqua_scoring_system": "CVSS V2",
          "first_found_date": "2020-04-29",
          "last_found_date": "2020-04-29",
          "ancestor_pkg": "",
          "sibling_pkg": "",
          "v_patch_applied_by": "",
          "v_patch_applied_on": "",
          "v_patch_reverted_by": "",
          "v_patch_reverted_on": "",
          "v_patch_enforced_by": "",
          "v_patch_enforced_on": "",
          "v_patch_status": "",
          "acknowledged_date": "0001-01-01T00:00:00Z",
          "ack_scope": "",
          "ack_comment": "",
          "ack_author": "",
          "ack_expiration_days": 0,
          "ack_expiration_configured_at": "0001-01-01T00:00:00Z",
          "ack_expiration_configured_by": "",
          "v_patch_policy_name": "",
          "v_patch_policy_enforce": false,
          "audit_events_count": 0,
          "block_events_count": 0,
          "image_workload_info": null,
          "base_image_vulnerability": false,
          "base_image_name": ""
        }
      ],
      "resource": {
        "type": "package",
        "format": "deb",
        "path": "",
        "name": "e2fsprogs",
        "version": "1.43.4-2",
        "arch": "amd64",
        "cpe": "pkg:/debian:9:e2fsprogs:1.43.4-2",
        "licenses": [
          "GPL2",
          "LGPL2"
        ],
        "hash": ""
      },
      "name": "DSA-4535-1",
      "description": "",
      "publish_date": "",
      "modification_date": "",
      "vendor_severity": "medium",
      "vendor_cvss2_score": 4.6,
      "vendor_cvss2_vectors": "AV:L/AC:L/Au:N/C:P/I:P/A:P",
      "vendor_statement": "",
      "vendor_url": "https://security-tracker.debian.org/tracker/DSA-4535-1",
      "nvd_severity": "medium",
      "nvd_cvss2_score": 4.6,
      "nvd_cvss2_vectors": "AV:L/AC:L/Au:N/C:P/I:P/A:P",
      "nvd_cvss3_severity": "medium",
      "nvd_cvss3_score": 6.7,
      "nvd_cvss3_vectors": "CVSS:3.1/AV:L/AC:L/PR:H/UI:N/S:U/C:H/I:H/A:H",
      "nvd_url": "",
      "fix_version": "1.43.4-2+deb9u1",
      "solution": "Upgrade package e2fsprogs to version 1.43.4-2+deb9u1 or above.",
      "classification": "",
      "qualys_ids": null,
      "aqua_score": 4.6,
      "aqua_severity": "medium",
      "aqua_vectors": "AV:L/AC:L/Au:N/C:P/I:P/A:P",
      "aqua_scoring_system": "CVSS V2",
      "first_found_date": "2020-04-29",
      "last_found_date": "2020-04-29",
      "ancestor_pkg": "",
      "sibling_pkg": "",
      "v_patch_applied_by": "",
      "v_patch_applied_on": "",
      "v_patch_reverted_by": "",
      "v_patch_reverted_on": "",
      "v_patch_enforced_by": "",
      "v_patch_enforced_on": "",
      "v_patch_status": "no_patch",
      "acknowledged_date": "1970-01-01T00:00:00Z",
      "ack_scope": "",
      "ack_comment": "",
      "ack_author": "",
      "ack_expiration_days": 0,
      "ack_expiration_configured_at": "1970-01-01T00:00:00Z",
      "ack_expiration_configured_by": "",
      "v_patch_policy_name": "",
      "v_patch_policy_enforce": false,
      "audit_events_count": 0,
      "block_events_count": 0,
      "image_workload_info": null,
      "base_image_vulnerability": false,
      "base_image_name": ""
    },
    {
      "registry": "Host Images",
      "image_repository_name": "registry.aquasec.com/server",
      "image_name": "registry.aquasec.com/server:4.6",
      "image_digest": "sha256:0bdf4519c786be605d0d0bec65144d5ffc7074f958be7799a9ebb168b8a863a6",
      "referenced_vulnerabilities": null,
      "resource": {
        "type": "package",
        "format": "apk",
        "path": "",
        "name": "db",
        "version": "5.3.28-r1",
        "arch": "x86_64",
        "cpe": "pkg:/alpine:3.9.5:db:5.3.28-r1",
        "licenses": [
          "custom"
        ],
        "hash": ""
      },
      "name": "CVE-2017-3606",
      "description": "Vulnerability in the Data Store component of Oracle Berkeley DB. The supported version that is affected is Prior to 6.2.32. Difficult to exploit vulnerability allows unauthenticated attacker with logon to the infrastructure where Data Store executes to compromise Data Store. Successful attacks require human interaction from a person other than the attacker. Successful attacks of this vulnerability can result in takeover of Data Store. CVSS 3.0 Base Score 7.0 (Confidentiality, Integrity and Availability impacts). CVSS Vector: (CVSS:3.0/AV:L/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:H).",
      "publish_date": "2017-04-24",
      "modification_date": "2019-10-03",
      "vendor_severity": "medium",
      "vendor_cvss2_score": 4.4,
      "vendor_cvss2_vectors": "AV:L/AC:M/Au:N/C:P/I:P/A:P",
      "vendor_statement": "",
      "vendor_url": "",
      "nvd_severity": "medium",
      "nvd_cvss2_score": 4.4,
      "nvd_cvss2_vectors": "AV:L/AC:M/Au:N/C:P/I:P/A:P",
      "nvd_cvss3_severity": "high",
      "nvd_cvss3_score": 7,
      "nvd_cvss3_vectors": "CVSS:3.0/AV:L/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:H",
      "nvd_url": "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2017-3606",
      "fix_version": "",
      "solution": "",
      "classification": "",
      "qualys_ids": null,
      "aqua_score": 4.4,
      "aqua_severity": "medium",
      "aqua_vectors": "AV:L/AC:M/Au:N/C:P/I:P/A:P",
      "aqua_scoring_system": "CVSS V2",
      "first_found_date": "2020-04-29",
      "last_found_date": "2020-04-29",
      "ancestor_pkg": "",
      "sibling_pkg": "",
      "v_patch_applied_by": "",
      "v_patch_applied_on": "",
      "v_patch_reverted_by": "",
      "v_patch_reverted_on": "",
      "v_patch_enforced_by": "",
      "v_patch_enforced_on": "",
      "v_patch_status": "no_patch",
      "acknowledged_date": "1970-01-01T00:00:00Z",
      "ack_scope": "",
      "ack_comment": "",
      "ack_author": "",
      "ack_expiration_days": 0,
      "ack_expiration_configured_at": "1970-01-01T00:00:00Z",
      "ack_expiration_configured_by": "",
      "v_patch_policy_name": "",
      "v_patch_policy_enforce": false,
      "audit_events_count": 0,
      "block_events_count": 0,
      "image_workload_info": null,
      "base_image_vulnerability": false,
      "base_image_name": ""
    },
    {
      "registry": "Host Images",
      "image_repository_name": "registry.aquasec.com/enforcer",
      "image_name": "registry.aquasec.com/enforcer:4.6",
      "image_digest": "sha256:39931a1c9fd34dbfab0d51bf20992c3b70228d3142056840024219eaccd1e160",
      "referenced_vulnerabilities": null,
      "resource": {
        "type": "package",
        "format": "apk",
        "path": "",
        "name": "db",
        "version": "5.3.28-r1",
        "arch": "x86_64",
        "cpe": "pkg:/alpine:3.7.3:db:5.3.28-r1",
        "licenses": [
          "custom"
        ],
        "hash": ""
      },
      "name": "CVE-2017-3606",
      "description": "Vulnerability in the Data Store component of Oracle Berkeley DB. The supported version that is affected is Prior to 6.2.32. Difficult to exploit vulnerability allows unauthenticated attacker with logon to the infrastructure where Data Store executes to compromise Data Store. Successful attacks require human interaction from a person other than the attacker. Successful attacks of this vulnerability can result in takeover of Data Store. CVSS 3.0 Base Score 7.0 (Confidentiality, Integrity and Availability impacts). CVSS Vector: (CVSS:3.0/AV:L/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:H).",
      "publish_date": "2017-04-24",
      "modification_date": "2019-10-03",
      "vendor_severity": "medium",
      "vendor_cvss2_score": 4.4,
      "vendor_cvss2_vectors": "AV:L/AC:M/Au:N/C:P/I:P/A:P",
      "vendor_statement": "",
      "vendor_url": "",
      "nvd_severity": "medium",
      "nvd_cvss2_score": 4.4,
      "nvd_cvss2_vectors": "AV:L/AC:M/Au:N/C:P/I:P/A:P",
      "nvd_cvss3_severity": "high",
      "nvd_cvss3_score": 7,
      "nvd_cvss3_vectors": "CVSS:3.0/AV:L/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:H",
      "nvd_url": "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2017-3606",
      "fix_version": "",
      "solution": "",
      "classification": "",
      "qualys_ids": null,
      "aqua_score": 4.4,
      "aqua_severity": "medium",
      "aqua_vectors": "AV:L/AC:M/Au:N/C:P/I:P/A:P",
      "aqua_scoring_system": "CVSS V2",
      "first_found_date": "2020-04-29",
      "last_found_date": "2020-04-29",
      "ancestor_pkg": "",
      "sibling_pkg": "",
      "v_patch_applied_by": "",
      "v_patch_applied_on": "",
      "v_patch_reverted_by": "",
      "v_patch_reverted_on": "",
      "v_patch_enforced_by": "",
      "v_patch_enforced_on": "",
      "v_patch_status": "no_patch",
      "acknowledged_date": "1970-01-01T00:00:00Z",
      "ack_scope": "",
      "ack_comment": "",
      "ack_author": "",
      "ack_expiration_days": 0,
      "ack_expiration_configured_at": "1970-01-01T00:00:00Z",
      "ack_expiration_configured_by": "",
      "v_patch_policy_name": "",
      "v_patch_policy_enforce": false,
      "audit_events_count": 0,
      "block_events_count": 0,
      "image_workload_info": null,
      "base_image_vulnerability": false,
      "base_image_name": ""
    },
    {
      "registry": "Host Images",
      "image_repository_name": "registry.aquasec.com/enforcer",
      "image_name": "registry.aquasec.com/enforcer:4.6",
      "image_digest": "sha256:39931a1c9fd34dbfab0d51bf20992c3b70228d3142056840024219eaccd1e160",
      "referenced_vulnerabilities": null,
      "resource": {
        "type": "package",
        "format": "apk",
        "path": "",
        "name": "libarchive",
        "version": "3.3.3-r1",
        "arch": "x86_64",
        "cpe": "pkg:/alpine:3.7.3:libarchive:3.3.3-r1",
        "licenses": [
          "BSD"
        ],
        "hash": ""
      },
      "name": "CVE-2018-1000879",
      "description": "libarchive version commit 379867ecb330b3a952fb7bfa7bffb7bbd5547205 onwards (release v3.3.0 onwards) contains a CWE-476: NULL Pointer Dereference vulnerability in ACL parser - libarchive/archive_acl.c, archive_acl_from_text_l() that can result in Crash/DoS. This attack appear to be exploitable via the victim must open a specially crafted archive file.",
      "publish_date": "2018-12-20",
      "modification_date": "2019-11-06",
      "vendor_severity": "medium",
      "vendor_cvss2_score": 4.3,
      "vendor_cvss2_vectors": "AV:N/AC:M/Au:N/C:N/I:N/A:P",
      "vendor_statement": "",
      "vendor_url": "",
      "nvd_severity": "medium",
      "nvd_cvss2_score": 4.3,
      "nvd_cvss2_vectors": "AV:N/AC:M/Au:N/C:N/I:N/A:P",
      "nvd_cvss3_severity": "medium",
      "nvd_cvss3_score": 6.5,
      "nvd_cvss3_vectors": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
      "nvd_url": "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2018-1000879",
      "fix_version": "",
      "solution": "",
      "classification": "",
      "qualys_ids": null,
      "aqua_score": 4.3,
      "aqua_severity": "medium",
      "aqua_vectors": "AV:N/AC:M/Au:N/C:N/I:N/A:P",
      "aqua_scoring_system": "CVSS V2",
      "first_found_date": "2020-04-29",
      "last_found_date": "2020-04-29",
      "ancestor_pkg": "",
      "sibling_pkg": "",
      "v_patch_applied_by": "",
      "v_patch_applied_on": "",
      "v_patch_reverted_by": "",
      "v_patch_reverted_on": "",
      "v_patch_enforced_by": "",
      "v_patch_enforced_on": "",
      "v_patch_status": "no_patch",
      "acknowledged_date": "1970-01-01T00:00:00Z",
      "ack_scope": "",
      "ack_comment": "",
      "ack_author": "",
      "ack_expiration_days": 0,
      "ack_expiration_configured_at": "1970-01-01T00:00:00Z",
      "ack_expiration_configured_by": "",
      "v_patch_policy_name": "",
      "v_patch_policy_enforce": false,
      "audit_events_count": 0,
      "block_events_count": 0,
      "image_workload_info": null,
      "base_image_vulnerability": false,
      "base_image_name": ""
    },
    {
      "registry": "Host Images",
      "image_repository_name": "registry.aquasec.com/enforcer",
      "image_name": "registry.aquasec.com/enforcer:4.6",
      "image_digest": "sha256:39931a1c9fd34dbfab0d51bf20992c3b70228d3142056840024219eaccd1e160",
      "referenced_vulnerabilities": null,
      "resource": {
        "type": "package",
        "format": "apk",
        "path": "",
        "name": "libarchive",
        "version": "3.3.3-r1",
        "arch": "x86_64",
        "cpe": "pkg:/alpine:3.7.3:libarchive:3.3.3-r1",
        "licenses": [
          "BSD"
        ],
        "hash": ""
      },
      "name": "CVE-2018-1000880",
      "description": "libarchive version commit 9693801580c0cf7c70e862d305270a16b52826a7 onwards (release v3.2.0 onwards) contains a CWE-20: Improper Input Validation vulnerability in WARC parser - libarchive/archive_read_support_format_warc.c, _warc_read() that can result in DoS - quasi-infinite run time and disk usage from tiny file. This attack appear to be exploitable via the victim must open a specially crafted WARC file.",
      "publish_date": "2018-12-20",
      "modification_date": "2019-10-21",
      "vendor_severity": "medium",
      "vendor_cvss2_score": 4.3,
      "vendor_cvss2_vectors": "AV:N/AC:M/Au:N/C:N/I:N/A:P",
      "vendor_statement": "",
      "vendor_url": "",
      "nvd_severity": "medium",
      "nvd_cvss2_score": 4.3,
      "nvd_cvss2_vectors": "AV:N/AC:M/Au:N/C:N/I:N/A:P",
      "nvd_cvss3_severity": "medium",
      "nvd_cvss3_score": 6.5,
      "nvd_cvss3_vectors": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
      "nvd_url": "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2018-1000880",
      "fix_version": "",
      "solution": "",
      "classification": "",
      "qualys_ids": null,
      "aqua_score": 4.3,
      "aqua_severity": "medium",
      "aqua_vectors": "AV:N/AC:M/Au:N/C:N/I:N/A:P",
      "aqua_scoring_system": "CVSS V2",
      "first_found_date": "2020-04-29",
      "last_found_date": "2020-04-29",
      "ancestor_pkg": "",
      "sibling_pkg": "",
      "v_patch_applied_by": "",
      "v_patch_applied_on": "",
      "v_patch_reverted_by": "",
      "v_patch_reverted_on": "",
      "v_patch_enforced_by": "",
      "v_patch_enforced_on": "",
      "v_patch_status": "no_patch",
      "acknowledged_date": "1970-01-01T00:00:00Z",
      "ack_scope": "",
      "ack_comment": "",
      "ack_author": "",
      "ack_expiration_days": 0,
      "ack_expiration_configured_at": "1970-01-01T00:00:00Z",
      "ack_expiration_configured_by": "",
      "v_patch_policy_name": "",
      "v_patch_policy_enforce": false,
      "audit_events_count": 0,
      "block_events_count": 0,
      "image_workload_info": null,
      "base_image_vulnerability": false,
      "base_image_name": ""
    },
    {
      "registry": "Host Images",
      "image_repository_name": "registry.aquasec.com/enforcer",
      "image_name": "registry.aquasec.com/enforcer:4.6",
      "image_digest": "sha256:39931a1c9fd34dbfab0d51bf20992c3b70228d3142056840024219eaccd1e160",
      "referenced_vulnerabilities": null,
      "resource": {
        "type": "package",
        "format": "apk",
        "path": "",
        "name": "libarchive",
        "version": "3.3.3-r1",
        "arch": "x86_64",
        "cpe": "pkg:/alpine:3.7.3:libarchive:3.3.3-r1",
        "licenses": [
          "BSD"
        ],
        "hash": ""
      },
      "name": "CVE-2019-1000019",
      "description": "libarchive version commit bf9aec176c6748f0ee7a678c5f9f9555b9a757c1 onwards (release v3.0.2 onwards) contains a CWE-125: Out-of-bounds Read vulnerability in 7zip decompression, archive_read_support_format_7zip.c, header_bytes() that can result in a crash (denial of service). This attack appears to be exploitable via the victim opening a specially crafted 7zip file.",
      "publish_date": "2019-02-04",
      "modification_date": "2019-11-06",
      "vendor_severity": "medium",
      "vendor_cvss2_score": 4.3,
      "vendor_cvss2_vectors": "AV:N/AC:M/Au:N/C:N/I:N/A:P",
      "vendor_statement": "",
      "vendor_url": "",
      "nvd_severity": "medium",
      "nvd_cvss2_score": 4.3,
      "nvd_cvss2_vectors": "AV:N/AC:M/Au:N/C:N/I:N/A:P",
      "nvd_cvss3_severity": "medium",
      "nvd_cvss3_score": 6.5,
      "nvd_cvss3_vectors": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
      "nvd_url": "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2019-1000019",
      "fix_version": "",
      "solution": "",
      "classification": "",
      "qualys_ids": null,
      "aqua_score": 4.3,
      "aqua_severity": "medium",
      "aqua_vectors": "AV:N/AC:M/Au:N/C:N/I:N/A:P",
      "aqua_scoring_system": "CVSS V2",
      "first_found_date": "2020-04-29",
      "last_found_date": "2020-04-29",
      "ancestor_pkg": "",
      "sibling_pkg": "",
      "v_patch_applied_by": "",
      "v_patch_applied_on": "",
      "v_patch_reverted_by": "",
      "v_patch_reverted_on": "",
      "v_patch_enforced_by": "",
      "v_patch_enforced_on": "",
      "v_patch_status": "no_patch",
      "acknowledged_date": "1970-01-01T00:00:00Z",
      "ack_scope": "",
      "ack_comment": "",
      "ack_author": "",
      "ack_expiration_days": 0,
      "ack_expiration_configured_at": "1970-01-01T00:00:00Z",
      "ack_expiration_configured_by": "",
      "v_patch_policy_name": "",
      "v_patch_policy_enforce": false,
      "audit_events_count": 0,
      "block_events_count": 0,
      "image_workload_info": null,
      "base_image_vulnerability": false,
      "base_image_name": ""
    },
    {
      "registry": "Host Images",
      "image_repository_name": "registry.aquasec.com/enforcer",
      "image_name": "registry.aquasec.com/enforcer:4.6",
      "image_digest": "sha256:39931a1c9fd34dbfab0d51bf20992c3b70228d3142056840024219eaccd1e160",
      "referenced_vulnerabilities": null,
      "resource": {
        "type": "package",
        "format": "apk",
        "path": "",
        "name": "libarchive",
        "version": "3.3.3-r1",
        "arch": "x86_64",
        "cpe": "pkg:/alpine:3.7.3:libarchive:3.3.3-r1",
        "licenses": [
          "BSD"
        ],
        "hash": ""
      },
      "name": "CVE-2019-1000020",
      "description": "libarchive version commit 5a98dcf8a86364b3c2c469c85b93647dfb139961 onwards (version v2.8.0 onwards) contains a CWE-835: Loop with Unreachable Exit Condition ('Infinite Loop') vulnerability in ISO9660 parser, archive_read_support_format_iso9660.c, read_CE()/parse_rockridge() that can result in DoS by infinite loop. This attack appears to be exploitable via the victim opening a specially crafted ISO9660 file.",
      "publish_date": "2019-02-04",
      "modification_date": "2019-11-06",
      "vendor_severity": "medium",
      "vendor_cvss2_score": 4.3,
      "vendor_cvss2_vectors": "AV:N/AC:M/Au:N/C:N/I:N/A:P",
      "vendor_statement": "",
      "vendor_url": "",
      "nvd_severity": "medium",
      "nvd_cvss2_score": 4.3,
      "nvd_cvss2_vectors": "AV:N/AC:M/Au:N/C:N/I:N/A:P",
      "nvd_cvss3_severity": "medium",
      "nvd_cvss3_score": 6.5,
      "nvd_cvss3_vectors": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
      "nvd_url": "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2019-1000020",
      "fix_version": "",
      "solution": "",
      "classification": "",
      "qualys_ids": null,
      "aqua_score": 4.3,
      "aqua_severity": "medium",
      "aqua_vectors": "AV:N/AC:M/Au:N/C:N/I:N/A:P",
      "aqua_scoring_system": "CVSS V2",
      "first_found_date": "2020-04-29",
      "last_found_date": "2020-04-29",
      "ancestor_pkg": "",
      "sibling_pkg": "",
      "v_patch_applied_by": "",
      "v_patch_applied_on": "",
      "v_patch_reverted_by": "",
      "v_patch_reverted_on": "",
      "v_patch_enforced_by": "",
      "v_patch_enforced_on": "",
      "v_patch_status": "no_patch",
      "acknowledged_date": "1970-01-01T00:00:00Z",
      "ack_scope": "",
      "ack_comment": "",
      "ack_author": "",
      "ack_expiration_days": 0,
      "ack_expiration_configured_at": "1970-01-01T00:00:00Z",
      "ack_expiration_configured_by": "",
      "v_patch_policy_name": "",
      "v_patch_policy_enforce": false,
      "audit_events_count": 0,
      "block_events_count": 0,
      "image_workload_info": null,
      "base_image_vulnerability": false,
      "base_image_name": ""
    },
    {
      "registry": "Host Images",
      "image_repository_name": "quay.io/kubernetes-ingress-controller/nginx-ingress-controller",
      "image_name": "quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.26.1",
      "image_digest": "sha256:29024c9c6e706357bebda26ea9a15064e77616f4d40c215ce81ae5e4b2a460aa",
      "referenced_vulnerabilities": [
        {
          "registry": "",
          "image_repository_name": "",
          "referenced_vulnerabilities": null,
          "resource": {
            "type": "",
            "format": "",
            "path": "",
            "name": "",
            "version": "",
            "arch": "",
            "cpe": "",
            "licenses": null,
            "hash": ""
          },
          "name": "CVE-2019-1563",
          "description": "In situations where an attacker receives automated notification of the success or failure of a decryption attempt an attacker, after sending a very large number of messages to be decrypted, can recover a CMS/PKCS7 transported encryption key or decrypt any RSA encrypted message that was encrypted with the public RSA key, using a Bleichenbacher padding oracle attack. Applications are not affected if they use a certificate together with the private RSA key to the CMS_decrypt or PKCS7_decrypt functions to select the correct recipient info to decrypt. Fixed in OpenSSL 1.1.1d (Affected 1.1.1-1.1.1c). Fixed in OpenSSL 1.1.0l (Affected 1.1.0-1.1.0k). Fixed in OpenSSL 1.0.2t (Affected 1.0.2-1.0.2s).",
          "publish_date": "2019-09-10",
          "modification_date": "2019-09-12",
          "vendor_severity": "medium",
          "vendor_cvss2_score": 4.3,
          "vendor_cvss2_vectors": "AV:N/AC:M/Au:N/C:P/I:N/A:N",
          "vendor_cvss3_severity": "low",
          "vendor_cvss3_score": 3.7,
          "vendor_cvss3_vectors": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:N/A:N",
          "vendor_statement": "https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=08229ad838c50f644d7e928e2eef147b4308ad64 (OpenSSL_1_1_1d)\nhttps://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=631f94db0065c78181ca9ba5546ebc8bb3884b97 (OpenSSL_1_1_0l)\nhttps://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=e21f8cf78a125cd3c8c0d1a1a6c8bb0b901f893f (OpenSSL_1_0_2t)\nhttps://www.openssl.org/news/secadv/20190910.txt",
          "vendor_url": "https://security-tracker.debian.org/tracker/CVE-2019-1563",
          "nvd_severity": "medium",
          "nvd_cvss2_score": 4.3,
          "nvd_cvss2_vectors": "AV:N/AC:M/Au:N/C:P/I:N/A:N",
          "nvd_cvss3_severity": "low",
          "nvd_cvss3_score": 3.7,
          "nvd_cvss3_vectors": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:N/A:N",
          "nvd_url": "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2019-1563",
          "fix_version": "",
          "solution": "",
          "classification": "",
          "qualys_ids": null,
          "aqua_score": 4.3,
          "aqua_severity": "medium",
          "aqua_vectors": "AV:N/AC:M/Au:N/C:P/I:N/A:N",
          "aqua_scoring_system": "CVSS V2",
          "first_found_date": "2020-04-29",
          "last_found_date": "2020-04-29",
          "ancestor_pkg": "",
          "sibling_pkg": "",
          "v_patch_applied_by": "",
          "v_patch_applied_on": "",
          "v_patch_reverted_by": "",
          "v_patch_reverted_on": "",
          "v_patch_enforced_by": "",
          "v_patch_enforced_on": "",
          "v_patch_status": "",
          "acknowledged_date": "0001-01-01T00:00:00Z",
          "ack_scope": "",
          "ack_comment": "",
          "ack_author": "",
          "ack_expiration_days": 0,
          "ack_expiration_configured_at": "0001-01-01T00:00:00Z",
          "ack_expiration_configured_by": "",
          "v_patch_policy_name": "",
          "v_patch_policy_enforce": false,
          "audit_events_count": 0,
          "block_events_count": 0,
          "image_workload_info": null,
          "base_image_vulnerability": false,
          "base_image_name": ""
        },
        {
          "registry": "",
          "image_repository_name": "",
          "referenced_vulnerabilities": null,
          "resource": {
            "type": "",
            "format": "",
            "path": "",
            "name": "",
            "version": "",
            "arch": "",
            "cpe": "",
            "licenses": null,
            "hash": ""
          },
          "name": "CVE-2019-1547",
          "description": "Normally in OpenSSL EC groups always have a co-factor present and this is used in side channel resistant code paths. However, in some cases, it is possible to construct a group using explicit parameters (instead of using a named curve). In those cases it is possible that such a group does not have the cofactor present. This can occur even where all the parameters match a known named curve. If such a curve is used then OpenSSL falls back to non-side channel resistant code paths which may result in full key recovery during an ECDSA signature operation. In order to be vulnerable an attacker would have to have the ability to time the creation of a large number of signatures where explicit parameters with no co-factor present are in use by an application using libcrypto. For the avoidance of doubt libssl is not vulnerable because explicit parameters are never used. Fixed in OpenSSL 1.1.1d (Affected 1.1.1-1.1.1c). Fixed in OpenSSL 1.1.0l (Affected 1.1.0-1.1.0k). Fixed in OpenSSL 1.0.2t (Affected 1.0.2-1.0.2s).",
          "publish_date": "2019-09-10",
          "modification_date": "2019-09-12",
          "vendor_severity": "low",
          "vendor_cvss2_score": 1.9,
          "vendor_cvss2_vectors": "AV:L/AC:M/Au:N/C:P/I:N/A:N",
          "vendor_cvss3_severity": "medium",
          "vendor_cvss3_score": 4.7,
          "vendor_cvss3_vectors": "CVSS:3.1/AV:L/AC:H/PR:L/UI:N/S:U/C:H/I:N/A:N",
          "vendor_statement": "https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=21c856b75d81eff61aa63b4f036bb64a85bf6d46 (OpenSSL_1_0_2t)\nhttps://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=7c1709c2da5414f5b6133d00a03fc8c5bf996c7a (OpenSSL_1_1_0l)\nhttps://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=30c22fa8b1d840036b8e203585738df62a03cec8 (OpenSSL_1_1_1d)\nhttps://www.openssl.org/news/secadv/20190910.txt",
          "vendor_url": "https://security-tracker.debian.org/tracker/CVE-2019-1547",
          "nvd_severity": "low",
          "nvd_cvss2_score": 1.9,
          "nvd_cvss2_vectors": "AV:L/AC:M/Au:N/C:P/I:N/A:N",
          "nvd_cvss3_severity": "medium",
          "nvd_cvss3_score": 4.7,
          "nvd_cvss3_vectors": "CVSS:3.1/AV:L/AC:H/PR:L/UI:N/S:U/C:H/I:N/A:N",
          "nvd_url": "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2019-1547",
          "fix_version": "",
          "solution": "",
          "classification": "",
          "qualys_ids": null,
          "aqua_score": 1.9,
          "aqua_severity": "low",
          "aqua_vectors": "AV:L/AC:M/Au:N/C:P/I:N/A:N",
          "aqua_scoring_system": "CVSS V2",
          "first_found_date": "2020-04-29",
          "last_found_date": "2020-04-29",
          "ancestor_pkg": "",
          "sibling_pkg": "",
          "v_patch_applied_by": "",
          "v_patch_applied_on": "",
          "v_patch_reverted_by": "",
          "v_patch_reverted_on": "",
          "v_patch_enforced_by": "",
          "v_patch_enforced_on": "",
          "v_patch_status": "",
          "acknowledged_date": "0001-01-01T00:00:00Z",
          "ack_scope": "",
          "ack_comment": "",
          "ack_author": "",
          "ack_expiration_days": 0,
          "ack_expiration_configured_at": "0001-01-01T00:00:00Z",
          "ack_expiration_configured_by": "",
          "v_patch_policy_name": "",
          "v_patch_policy_enforce": false,
          "audit_events_count": 0,
          "block_events_count": 0,
          "image_workload_info": null,
          "base_image_vulnerability": false,
          "base_image_name": ""
        }
      ],
      "resource": {
        "type": "package",
        "format": "deb",
        "path": "",
        "name": "openssl",
        "version": "1.1.1c-1",
        "arch": "amd64",
        "cpe": "pkg:/debian:10:openssl:1.1.1c-1",
        "licenses": null,
        "hash": ""
      },
      "name": "DSA-4539-1",
      "description": "",
      "publish_date": "",
      "modification_date": "",
      "vendor_severity": "medium",
      "vendor_cvss2_score": 4.3,
      "vendor_cvss2_vectors": "AV:N/AC:M/Au:N/C:P/I:N/A:N",
      "vendor_statement": "",
      "vendor_url": "https://security-tracker.debian.org/tracker/DSA-4539-1",
      "nvd_severity": "medium",
      "nvd_cvss2_score": 4.3,
      "nvd_cvss2_vectors": "AV:N/AC:M/Au:N/C:P/I:N/A:N",
      "nvd_cvss3_severity": "medium",
      "nvd_cvss3_score": 4.7,
      "nvd_cvss3_vectors": "CVSS:3.1/AV:L/AC:H/PR:L/UI:N/S:U/C:H/I:N/A:N",
      "nvd_url": "",
      "fix_version": "1.1.1d-0+deb10u1",
      "solution": "Upgrade package openssl to version 1.1.1d-0+deb10u1 or above.",
      "classification": "",
      "qualys_ids": null,
      "aqua_score": 4.3,
      "aqua_severity": "medium",
      "aqua_vectors": "AV:N/AC:M/Au:N/C:P/I:N/A:N",
      "aqua_scoring_system": "CVSS V2",
      "first_found_date": "2020-04-29",
      "last_found_date": "2020-04-29",
      "ancestor_pkg": "",
      "sibling_pkg": "",
      "v_patch_applied_by": "",
      "v_patch_applied_on": "",
      "v_patch_reverted_by": "",
      "v_patch_reverted_on": "",
      "v_patch_enforced_by": "",
      "v_patch_enforced_on": "",
      "v_patch_status": "no_patch",
      "acknowledged_date": "1970-01-01T00:00:00Z",
      "ack_scope": "",
      "ack_comment": "",
      "ack_author": "",
      "ack_expiration_days": 0,
      "ack_expiration_configured_at": "1970-01-01T00:00:00Z",
      "ack_expiration_configured_by": "",
      "v_patch_policy_name": "",
      "v_patch_policy_enforce": false,
      "audit_events_count": 0,
      "block_events_count": 0,
      "image_workload_info": null,
      "base_image_vulnerability": false,
      "base_image_name": ""
    },
    {
      "registry": "Host Images",
      "image_repository_name": "gcr.io/google-containers/hyperkube",
      "image_name": "gcr.io/google-containers/hyperkube:v1.16.6",
      "image_digest": "sha256:ae6fea104d3daa8321f9ba27767b3f8f25eefc37d6cbfea7a611da15cacae153",
      "referenced_vulnerabilities": null,
      "resource": {
        "type": "file",
        "format": "",
        "path": "/usr/lib/python2.7/ssl.py",
        "name": "",
        "version": "",
        "arch": "",
        "cpe": "file:/aa7087816fc268be469f8bc3d607944d9ef9b59b",
        "licenses": null,
        "hash": "sha1:aa7087816fc268be469f8bc3d607944d9ef9b59b"
      },
      "name": "CVE-2013-2099",
      "description": "Algorithmic complexity vulnerability in the ssl.match_hostname function in Python 3.2.x, 3.3.x, and earlier, and unspecified versions of python-backports-ssl_match_hostname as used for older Python versions, allows remote attackers to cause a denial of service (CPU consumption) via multiple wildcard characters in the common name in a certificate.",
      "publish_date": "2013-10-09",
      "modification_date": "2016-06-09",
      "vendor_severity": "medium",
      "vendor_cvss2_score": 4.3,
      "vendor_cvss2_vectors": "",
      "vendor_statement": "",
      "vendor_url": "http://bugs.python.org/issue17980",
      "nvd_severity": "medium",
      "nvd_cvss2_score": 4.3,
      "nvd_cvss2_vectors": "AV:N/AC:M/Au:N/C:N/I:N/A:P",
      "nvd_cvss3_severity": "",
      "nvd_cvss3_score": 0,
      "nvd_cvss3_vectors": "",
      "nvd_url": "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2013-2099",
      "fix_version": "3.3.2-r1, 3.2.5-r1, 2.6.8, 2.7.3-r1",
      "solution": "All Python 3.3 users should upgrade to the latest version >= python-3.3.2-r1\nAll Python 3.2 users should upgrade to the latest version >= python-3.2.5-r1\nAll Python 2.6 users should upgrade to the latest version >= python-2.6.8\nAll Python 2.7 users should upgrade to the latest version >= python-2.7.3-r1\n\n3.4",
      "classification": "",
      "qualys_ids": null,
      "aqua_score": 4.3,
      "aqua_severity": "medium",
      "aqua_vectors": "",
      "aqua_scoring_system": "CVSS V2",
      "first_found_date": "2020-04-29",
      "last_found_date": "2020-04-29",
      "ancestor_pkg": "",
      "sibling_pkg": "",
      "v_patch_applied_by": "",
      "v_patch_applied_on": "",
      "v_patch_reverted_by": "",
      "v_patch_reverted_on": "",
      "v_patch_enforced_by": "",
      "v_patch_enforced_on": "",
      "v_patch_status": "patch_available",
      "acknowledged_date": "1970-01-01T00:00:00Z",
      "ack_scope": "",
      "ack_comment": "",
      "ack_author": "",
      "ack_expiration_days": 0,
      "ack_expiration_configured_at": "1970-01-01T00:00:00Z",
      "ack_expiration_configured_by": "",
      "v_patch_policy_name": "",
      "v_patch_policy_enforce": false,
      "audit_events_count": 0,
      "block_events_count": 0,
      "image_workload_info": null,
      "base_image_vulnerability": false,
      "base_image_name": ""
    },
    {
      "registry": "Host Images",
      "image_repository_name": "gcr.io/google-containers/hyperkube",
      "image_name": "gcr.io/google-containers/hyperkube:v1.16.6",
      "image_digest": "sha256:ae6fea104d3daa8321f9ba27767b3f8f25eefc37d6cbfea7a611da15cacae153",
      "referenced_vulnerabilities": [
        {
          "registry": "",
          "image_repository_name": "",
          "referenced_vulnerabilities": null,
          "resource": {
            "type": "",
            "format": "",
            "path": "",
            "name": "",
            "version": "",
            "arch": "",
            "cpe": "",
            "licenses": null,
            "hash": ""
          },
          "name": "CVE-2019-1563",
          "description": "In situations where an attacker receives automated notification of the success or failure of a decryption attempt an attacker, after sending a very large number of messages to be decrypted, can recover a CMS/PKCS7 transported encryption key or decrypt any RSA encrypted message that was encrypted with the public RSA key, using a Bleichenbacher padding oracle attack. Applications are not affected if they use a certificate together with the private RSA key to the CMS_decrypt or PKCS7_decrypt functions to select the correct recipient info to decrypt. Fixed in OpenSSL 1.1.1d (Affected 1.1.1-1.1.1c). Fixed in OpenSSL 1.1.0l (Affected 1.1.0-1.1.0k). Fixed in OpenSSL 1.0.2t (Affected 1.0.2-1.0.2s).",
          "publish_date": "2019-09-10",
          "modification_date": "2019-09-12",
          "vendor_severity": "medium",
          "vendor_cvss2_score": 4.3,
          "vendor_cvss2_vectors": "AV:N/AC:M/Au:N/C:P/I:N/A:N",
          "vendor_cvss3_severity": "low",
          "vendor_cvss3_score": 3.7,
          "vendor_cvss3_vectors": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:N/A:N",
          "vendor_statement": "https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=08229ad838c50f644d7e928e2eef147b4308ad64 (OpenSSL_1_1_1d)\nhttps://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=631f94db0065c78181ca9ba5546ebc8bb3884b97 (OpenSSL_1_1_0l)\nhttps://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=e21f8cf78a125cd3c8c0d1a1a6c8bb0b901f893f (OpenSSL_1_0_2t)\nhttps://www.openssl.org/news/secadv/20190910.txt",
          "vendor_url": "https://security-tracker.debian.org/tracker/CVE-2019-1563",
          "nvd_severity": "medium",
          "nvd_cvss2_score": 4.3,
          "nvd_cvss2_vectors": "AV:N/AC:M/Au:N/C:P/I:N/A:N",
          "nvd_cvss3_severity": "low",
          "nvd_cvss3_score": 3.7,
          "nvd_cvss3_vectors": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:N/A:N",
          "nvd_url": "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2019-1563",
          "fix_version": "",
          "solution": "",
          "classification": "",
          "qualys_ids": null,
          "aqua_score": 4.3,
          "aqua_severity": "medium",
          "aqua_vectors": "AV:N/AC:M/Au:N/C:P/I:N/A:N",
          "aqua_scoring_system": "CVSS V2",
          "first_found_date": "2020-04-29",
          "last_found_date": "2020-04-29",
          "ancestor_pkg": "",
          "sibling_pkg": "",
          "v_patch_applied_by": "",
          "v_patch_applied_on": "",
          "v_patch_reverted_by": "",
          "v_patch_reverted_on": "",
          "v_patch_enforced_by": "",
          "v_patch_enforced_on": "",
          "v_patch_status": "",
          "acknowledged_date": "0001-01-01T00:00:00Z",
          "ack_scope": "",
          "ack_comment": "",
          "ack_author": "",
          "ack_expiration_days": 0,
          "ack_expiration_configured_at": "0001-01-01T00:00:00Z",
          "ack_expiration_configured_by": "",
          "v_patch_policy_name": "",
          "v_patch_policy_enforce": false,
          "audit_events_count": 0,
          "block_events_count": 0,
          "image_workload_info": null,
          "base_image_vulnerability": false,
          "base_image_name": ""
        },
        {
          "registry": "",
          "image_repository_name": "",
          "referenced_vulnerabilities": null,
          "resource": {
            "type": "",
            "format": "",
            "path": "",
            "name": "",
            "version": "",
            "arch": "",
            "cpe": "",
            "licenses": null,
            "hash": ""
          },
          "name": "CVE-2019-1547",
          "description": "Normally in OpenSSL EC groups always have a co-factor present and this is used in side channel resistant code paths. However, in some cases, it is possible to construct a group using explicit parameters (instead of using a named curve). In those cases it is possible that such a group does not have the cofactor present. This can occur even where all the parameters match a known named curve. If such a curve is used then OpenSSL falls back to non-side channel resistant code paths which may result in full key recovery during an ECDSA signature operation. In order to be vulnerable an attacker would have to have the ability to time the creation of a large number of signatures where explicit parameters with no co-factor present are in use by an application using libcrypto. For the avoidance of doubt libssl is not vulnerable because explicit parameters are never used. Fixed in OpenSSL 1.1.1d (Affected 1.1.1-1.1.1c). Fixed in OpenSSL 1.1.0l (Affected 1.1.0-1.1.0k). Fixed in OpenSSL 1.0.2t (Affected 1.0.2-1.0.2s).",
          "publish_date": "2019-09-10",
          "modification_date": "2019-09-12",
          "vendor_severity": "low",
          "vendor_cvss2_score": 1.9,
          "vendor_cvss2_vectors": "AV:L/AC:M/Au:N/C:P/I:N/A:N",
          "vendor_cvss3_severity": "medium",
          "vendor_cvss3_score": 4.7,
          "vendor_cvss3_vectors": "CVSS:3.1/AV:L/AC:H/PR:L/UI:N/S:U/C:H/I:N/A:N",
          "vendor_statement": "https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=21c856b75d81eff61aa63b4f036bb64a85bf6d46 (OpenSSL_1_0_2t)\nhttps://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=7c1709c2da5414f5b6133d00a03fc8c5bf996c7a (OpenSSL_1_1_0l)\nhttps://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=30c22fa8b1d840036b8e203585738df62a03cec8 (OpenSSL_1_1_1d)\nhttps://www.openssl.org/news/secadv/20190910.txt",
          "vendor_url": "https://security-tracker.debian.org/tracker/CVE-2019-1547",
          "nvd_severity": "low",
          "nvd_cvss2_score": 1.9,
          "nvd_cvss2_vectors": "AV:L/AC:M/Au:N/C:P/I:N/A:N",
          "nvd_cvss3_severity": "medium",
          "nvd_cvss3_score": 4.7,
          "nvd_cvss3_vectors": "CVSS:3.1/AV:L/AC:H/PR:L/UI:N/S:U/C:H/I:N/A:N",
          "nvd_url": "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2019-1547",
          "fix_version": "",
          "solution": "",
          "classification": "",
          "qualys_ids": null,
          "aqua_score": 1.9,
          "aqua_severity": "low",
          "aqua_vectors": "AV:L/AC:M/Au:N/C:P/I:N/A:N",
          "aqua_scoring_system": "CVSS V2",
          "first_found_date": "2020-04-29",
          "last_found_date": "2020-04-29",
          "ancestor_pkg": "",
          "sibling_pkg": "",
          "v_patch_applied_by": "",
          "v_patch_applied_on": "",
          "v_patch_reverted_by": "",
          "v_patch_reverted_on": "",
          "v_patch_enforced_by": "",
          "v_patch_enforced_on": "",
          "v_patch_status": "",
          "acknowledged_date": "0001-01-01T00:00:00Z",
          "ack_scope": "",
          "ack_comment": "",
          "ack_author": "",
          "ack_expiration_days": 0,
          "ack_expiration_configured_at": "0001-01-01T00:00:00Z",
          "ack_expiration_configured_by": "",
          "v_patch_policy_name": "",
          "v_patch_policy_enforce": false,
          "audit_events_count": 0,
          "block_events_count": 0,
          "image_workload_info": null,
          "base_image_vulnerability": false,
          "base_image_name": ""
        }
      ],
      "resource": {
        "type": "package",
        "format": "deb",
        "path": "",
        "name": "openssl",
        "version": "1.1.0j-1~deb9u1",
        "arch": "amd64",
        "cpe": "pkg:/debian:9:openssl:1.1.0j-1~deb9u1",
        "licenses": null,
        "hash": ""
      },
      "name": "DSA-4539-1",
      "description": "",
      "publish_date": "",
      "modification_date": "",
      "vendor_severity": "medium",
      "vendor_cvss2_score": 4.3,
      "vendor_cvss2_vectors": "AV:N/AC:M/Au:N/C:P/I:N/A:N",
      "vendor_statement": "",
      "vendor_url": "https://security-tracker.debian.org/tracker/DSA-4539-1",
      "nvd_severity": "medium",
      "nvd_cvss2_score": 4.3,
      "nvd_cvss2_vectors": "AV:N/AC:M/Au:N/C:P/I:N/A:N",
      "nvd_cvss3_severity": "medium",
      "nvd_cvss3_score": 4.7,
      "nvd_cvss3_vectors": "CVSS:3.1/AV:L/AC:H/PR:L/UI:N/S:U/C:H/I:N/A:N",
      "nvd_url": "",
      "fix_version": "1.1.0l-1~deb9u1",
      "solution": "Upgrade package openssl to version 1.1.0l-1~deb9u1 or above.",
      "classification": "",
      "qualys_ids": null,
      "aqua_score": 4.3,
      "aqua_severity": "medium",
      "aqua_vectors": "AV:N/AC:M/Au:N/C:P/I:N/A:N",
      "aqua_scoring_system": "CVSS V2",
      "first_found_date": "2020-04-29",
      "last_found_date": "2020-04-29",
      "ancestor_pkg": "",
      "sibling_pkg": "",
      "v_patch_applied_by": "",
      "v_patch_applied_on": "",
      "v_patch_reverted_by": "",
      "v_patch_reverted_on": "",
      "v_patch_enforced_by": "",
      "v_patch_enforced_on": "",
      "v_patch_status": "no_patch",
      "acknowledged_date": "1970-01-01T00:00:00Z",
      "ack_scope": "",
      "ack_comment": "",
      "ack_author": "",
      "ack_expiration_days": 0,
      "ack_expiration_configured_at": "1970-01-01T00:00:00Z",
      "ack_expiration_configured_by": "",
      "v_patch_policy_name": "",
      "v_patch_policy_enforce": false,
      "audit_events_count": 0,
      "block_events_count": 0,
      "image_workload_info": null,
      "base_image_vulnerability": false,
      "base_image_name": ""
    },
    {
      "registry": "Host Images",
      "image_repository_name": "digitalocean/do-agent",
      "image_name": "digitalocean/do-agent:3",
      "image_digest": "sha256:794213c682dcae17b12d06a42292b2fb57d8f4f2345b3d0a5acbc96b26d55c5f",
      "referenced_vulnerabilities": null,
      "resource": {
        "type": "executable",
        "format": "",
        "path": "/usr/bin/openssl",
        "name": "openssl",
        "version": "1.1.0k",
        "arch": "",
        "cpe": "cpe:/a:openssl:openssl:1.1.0k",
        "licenses": null,
        "hash": ""
      },
      "name": "CVE-2019-1563",
      "description": "In situations where an attacker receives automated notification of the success or failure of a decryption attempt an attacker, after sending a very large number of messages to be decrypted, can recover a CMS/PKCS7 transported encryption key or decrypt any RSA encrypted message that was encrypted with the public RSA key, using a Bleichenbacher padding oracle attack. Applications are not affected if they use a certificate together with the private RSA key to the CMS_decrypt or PKCS7_decrypt functions to select the correct recipient info to decrypt. Fixed in OpenSSL 1.1.1d (Affected 1.1.1-1.1.1c). Fixed in OpenSSL 1.1.0l (Affected 1.1.0-1.1.0k). Fixed in OpenSSL 1.0.2t (Affected 1.0.2-1.0.2s).",
      "publish_date": "2019-09-10",
      "modification_date": "2019-09-12",
      "vendor_severity": "medium",
      "vendor_cvss2_score": 4.3,
      "vendor_cvss2_vectors": "AV:N/AC:M/Au:N/C:P/I:N/A:N",
      "vendor_statement": "",
      "vendor_url": "",
      "nvd_severity": "medium",
      "nvd_cvss2_score": 4.3,
      "nvd_cvss2_vectors": "AV:N/AC:M/Au:N/C:P/I:N/A:N",
      "nvd_cvss3_severity": "low",
      "nvd_cvss3_score": 3.7,
      "nvd_cvss3_vectors": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:N/A:N",
      "nvd_url": "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2019-1563",
      "fix_version": "",
      "solution": "",
      "classification": "",
      "qualys_ids": null,
      "aqua_score": 4.3,
      "aqua_severity": "medium",
      "aqua_vectors": "AV:N/AC:M/Au:N/C:P/I:N/A:N",
      "aqua_scoring_system": "CVSS V2",
      "first_found_date": "2020-04-29",
      "last_found_date": "2020-04-29",
      "ancestor_pkg": "",
      "sibling_pkg": "",
      "v_patch_applied_by": "",
      "v_patch_applied_on": "",
      "v_patch_reverted_by": "",
      "v_patch_reverted_on": "",
      "v_patch_enforced_by": "",
      "v_patch_enforced_on": "",
      "v_patch_status": "no_patch",
      "acknowledged_date": "1970-01-01T00:00:00Z",
      "ack_scope": "",
      "ack_comment": "",
      "ack_author": "",
      "ack_expiration_days": 0,
      "ack_expiration_configured_at": "1970-01-01T00:00:00Z",
      "ack_expiration_configured_by": "",
      "v_patch_policy_name": "",
      "v_patch_policy_enforce": false,
      "audit_events_count": 0,
      "block_events_count": 0,
      "image_workload_info": null,
      "base_image_vulnerability": false,
      "base_image_name": ""
    },
    {
      "registry": "Host Images",
      "image_repository_name": "registry.aquasec.com/server",
      "image_name": "registry.aquasec.com/server:4.6",
      "image_digest": "sha256:0bdf4519c786be605d0d0bec65144d5ffc7074f958be7799a9ebb168b8a863a6",
      "referenced_vulnerabilities": null,
      "resource": {
        "type": "package",
        "format": "apk",
        "path": "",
        "name": "db",
        "version": "5.3.28-r1",
        "arch": "x86_64",
        "cpe": "pkg:/alpine:3.9.5:db:5.3.28-r1",
        "licenses": [
          "custom"
        ],
        "hash": ""
      },
      "name": "CVE-2017-3604",
      "description": "Vulnerability in the Data Store component of Oracle Berkeley DB. The supported version that is affected is Prior to 6.2.32. Difficult to exploit vulnerability allows unauthenticated attacker with logon to the infrastructure where Data Store executes to compromise Data Store. Successful attacks require human interaction from a person other than the attacker. Successful attacks of this vulnerability can result in takeover of Data Store. CVSS 3.0 Base Score 7.0 (Confidentiality, Integrity and Availability impacts). CVSS Vector: (CVSS:3.0/AV:L/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:H).",
      "publish_date": "2017-04-24",
      "modification_date": "2019-10-03",
      "vendor_severity": "low",
      "vendor_cvss2_score": 3.7,
      "vendor_cvss2_vectors": "AV:L/AC:H/Au:N/C:P/I:P/A:P",
      "vendor_statement": "",
      "vendor_url": "",
      "nvd_severity": "low",
      "nvd_cvss2_score": 3.7,
      "nvd_cvss2_vectors": "AV:L/AC:H/Au:N/C:P/I:P/A:P",
      "nvd_cvss3_severity": "high",
      "nvd_cvss3_score": 7,
      "nvd_cvss3_vectors": "CVSS:3.0/AV:L/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:H",
      "nvd_url": "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2017-3604",
      "fix_version": "",
      "solution": "",
      "classification": "",
      "qualys_ids": null,
      "aqua_score": 3.7,
      "aqua_severity": "low",
      "aqua_vectors": "AV:L/AC:H/Au:N/C:P/I:P/A:P",
      "aqua_scoring_system": "CVSS V2",
      "first_found_date": "2020-04-29",
      "last_found_date": "2020-04-29",
      "ancestor_pkg": "",
      "sibling_pkg": "",
      "v_patch_applied_by": "",
      "v_patch_applied_on": "",
      "v_patch_reverted_by": "",
      "v_patch_reverted_on": "",
      "v_patch_enforced_by": "",
      "v_patch_enforced_on": "",
      "v_patch_status": "no_patch",
      "acknowledged_date": "1970-01-01T00:00:00Z",
      "ack_scope": "",
      "ack_comment": "",
      "ack_author": "",
      "ack_expiration_days": 0,
      "ack_expiration_configured_at": "1970-01-01T00:00:00Z",
      "ack_expiration_configured_by": "",
      "v_patch_policy_name": "",
      "v_patch_policy_enforce": false,
      "audit_events_count": 0,
      "block_events_count": 0,
      "image_workload_info": null,
      "base_image_vulnerability": false,
      "base_image_name": ""
    },
    {
      "registry": "Host Images",
      "image_repository_name": "registry.aquasec.com/server",
      "image_name": "registry.aquasec.com/server:4.6",
      "image_digest": "sha256:0bdf4519c786be605d0d0bec65144d5ffc7074f958be7799a9ebb168b8a863a6",
      "referenced_vulnerabilities": null,
      "resource": {
        "type": "package",
        "format": "apk",
        "path": "",
        "name": "db",
        "version": "5.3.28-r1",
        "arch": "x86_64",
        "cpe": "pkg:/alpine:3.9.5:db:5.3.28-r1",
        "licenses": [
          "custom"
        ],
        "hash": ""
      },
      "name": "CVE-2017-3605",
      "description": "Vulnerability in the Data Store component of Oracle Berkeley DB. The supported version that is affected is Prior to 6.2.32. Difficult to exploit vulnerability allows unauthenticated attacker with logon to the infrastructure where Data Store executes to compromise Data Store. Successful attacks require human interaction from a person other than the attacker. Successful attacks of this vulnerability can result in takeover of Data Store. CVSS 3.0 Base Score 7.0 (Confidentiality, Integrity and Availability impacts). CVSS Vector: (CVSS:3.0/AV:L/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:H).",
      "publish_date": "2017-04-24",
      "modification_date": "2019-10-03",
      "vendor_severity": "low",
      "vendor_cvss2_score": 3.7,
      "vendor_cvss2_vectors": "AV:L/AC:H/Au:N/C:P/I:P/A:P",
      "vendor_statement": "",
      "vendor_url": "",
      "nvd_severity": "low",
      "nvd_cvss2_score": 3.7,
      "nvd_cvss2_vectors": "AV:L/AC:H/Au:N/C:P/I:P/A:P",
      "nvd_cvss3_severity": "high",
      "nvd_cvss3_score": 7,
      "nvd_cvss3_vectors": "CVSS:3.0/AV:L/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:H",
      "nvd_url": "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2017-3605",
      "fix_version": "",
      "solution": "",
      "classification": "",
      "qualys_ids": null,
      "aqua_score": 3.7,
      "aqua_severity": "low",
      "aqua_vectors": "AV:L/AC:H/Au:N/C:P/I:P/A:P",
      "aqua_scoring_system": "CVSS V2",
      "first_found_date": "2020-04-29",
      "last_found_date": "2020-04-29",
      "ancestor_pkg": "",
      "sibling_pkg": "",
      "v_patch_applied_by": "",
      "v_patch_applied_on": "",
      "v_patch_reverted_by": "",
      "v_patch_reverted_on": "",
      "v_patch_enforced_by": "",
      "v_patch_enforced_on": "",
      "v_patch_status": "no_patch",
      "acknowledged_date": "1970-01-01T00:00:00Z",
      "ack_scope": "",
      "ack_comment": "",
      "ack_author": "",
      "ack_expiration_days": 0,
      "ack_expiration_configured_at": "1970-01-01T00:00:00Z",
      "ack_expiration_configured_by": "",
      "v_patch_policy_name": "",
      "v_patch_policy_enforce": false,
      "audit_events_count": 0,
      "block_events_count": 0,
      "image_workload_info": null,
      "base_image_vulnerability": false,
      "base_image_name": ""
    },
    {
      "registry": "Host Images",
      "image_repository_name": "registry.aquasec.com/server",
      "image_name": "registry.aquasec.com/server:4.6",
      "image_digest": "sha256:0bdf4519c786be605d0d0bec65144d5ffc7074f958be7799a9ebb168b8a863a6",
      "referenced_vulnerabilities": null,
      "resource": {
        "type": "package",
        "format": "apk",
        "path": "",
        "name": "db",
        "version": "5.3.28-r1",
        "arch": "x86_64",
        "cpe": "pkg:/alpine:3.9.5:db:5.3.28-r1",
        "licenses": [
          "custom"
        ],
        "hash": ""
      },
      "name": "CVE-2017-3607",
      "description": "Vulnerability in the Data Store component of Oracle Berkeley DB. The supported version that is affected is Prior to 6.2.32. Difficult to exploit vulnerability allows unauthenticated attacker with logon to the infrastructure where Data Store executes to compromise Data Store. Successful attacks require human interaction from a person other than the attacker. Successful attacks of this vulnerability can result in takeover of Data Store. CVSS 3.0 Base Score 7.0 (Confidentiality, Integrity and Availability impacts). CVSS Vector: (CVSS:3.0/AV:L/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:H).",
      "publish_date": "2017-04-24",
      "modification_date": "2019-10-03",
      "vendor_severity": "low",
      "vendor_cvss2_score": 3.7,
      "vendor_cvss2_vectors": "AV:L/AC:H/Au:N/C:P/I:P/A:P",
      "vendor_statement": "",
      "vendor_url": "",
      "nvd_severity": "low",
      "nvd_cvss2_score": 3.7,
      "nvd_cvss2_vectors": "AV:L/AC:H/Au:N/C:P/I:P/A:P",
      "nvd_cvss3_severity": "high",
      "nvd_cvss3_score": 7,
      "nvd_cvss3_vectors": "CVSS:3.0/AV:L/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:H",
      "nvd_url": "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2017-3607",
      "fix_version": "",
      "solution": "",
      "classification": "",
      "qualys_ids": null,
      "aqua_score": 3.7,
      "aqua_severity": "low",
      "aqua_vectors": "AV:L/AC:H/Au:N/C:P/I:P/A:P",
      "aqua_scoring_system": "CVSS V2",
      "first_found_date": "2020-04-29",
      "last_found_date": "2020-04-29",
      "ancestor_pkg": "",
      "sibling_pkg": "",
      "v_patch_applied_by": "",
      "v_patch_applied_on": "",
      "v_patch_reverted_by": "",
      "v_patch_reverted_on": "",
      "v_patch_enforced_by": "",
      "v_patch_enforced_on": "",
      "v_patch_status": "no_patch",
      "acknowledged_date": "1970-01-01T00:00:00Z",
      "ack_scope": "",
      "ack_comment": "",
      "ack_author": "",
      "ack_expiration_days": 0,
      "ack_expiration_configured_at": "1970-01-01T00:00:00Z",
      "ack_expiration_configured_by": "",
      "v_patch_policy_name": "",
      "v_patch_policy_enforce": false,
      "audit_events_count": 0,
      "block_events_count": 0,
      "image_workload_info": null,
      "base_image_vulnerability": false,
      "base_image_name": ""
    },
    {
      "registry": "Host Images",
      "image_repository_name": "registry.aquasec.com/server",
      "image_name": "registry.aquasec.com/server:4.6",
      "image_digest": "sha256:0bdf4519c786be605d0d0bec65144d5ffc7074f958be7799a9ebb168b8a863a6",
      "referenced_vulnerabilities": null,
      "resource": {
        "type": "package",
        "format": "apk",
        "path": "",
        "name": "db",
        "version": "5.3.28-r1",
        "arch": "x86_64",
        "cpe": "pkg:/alpine:3.9.5:db:5.3.28-r1",
        "licenses": [
          "custom"
        ],
        "hash": ""
      },
      "name": "CVE-2017-3608",
      "description": "Vulnerability in the Data Store component of Oracle Berkeley DB. The supported version that is affected is Prior to 6.2.32. Difficult to exploit vulnerability allows unauthenticated attacker with logon to the infrastructure where Data Store executes to compromise Data Store. Successful attacks require human interaction from a person other than the attacker. Successful attacks of this vulnerability can result in takeover of Data Store. CVSS 3.0 Base Score 7.0 (Confidentiality, Integrity and Availability impacts). CVSS Vector: (CVSS:3.0/AV:L/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:H).",
      "publish_date": "2017-04-24",
      "modification_date": "2019-10-03",
      "vendor_severity": "low",
      "vendor_cvss2_score": 3.7,
      "vendor_cvss2_vectors": "AV:L/AC:H/Au:N/C:P/I:P/A:P",
      "vendor_statement": "",
      "vendor_url": "",
      "nvd_severity": "low",
      "nvd_cvss2_score": 3.7,
      "nvd_cvss2_vectors": "AV:L/AC:H/Au:N/C:P/I:P/A:P",
      "nvd_cvss3_severity": "high",
      "nvd_cvss3_score": 7,
      "nvd_cvss3_vectors": "CVSS:3.0/AV:L/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:H",
      "nvd_url": "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2017-3608",
      "fix_version": "",
      "solution": "",
      "classification": "",
      "qualys_ids": null,
      "aqua_score": 3.7,
      "aqua_severity": "low",
      "aqua_vectors": "AV:L/AC:H/Au:N/C:P/I:P/A:P",
      "aqua_scoring_system": "CVSS V2",
      "first_found_date": "2020-04-29",
      "last_found_date": "2020-04-29",
      "ancestor_pkg": "",
      "sibling_pkg": "",
      "v_patch_applied_by": "",
      "v_patch_applied_on": "",
      "v_patch_reverted_by": "",
      "v_patch_reverted_on": "",
      "v_patch_enforced_by": "",
      "v_patch_enforced_on": "",
      "v_patch_status": "no_patch",
      "acknowledged_date": "1970-01-01T00:00:00Z",
      "ack_scope": "",
      "ack_comment": "",
      "ack_author": "",
      "ack_expiration_days": 0,
      "ack_expiration_configured_at": "1970-01-01T00:00:00Z",
      "ack_expiration_configured_by": "",
      "v_patch_policy_name": "",
      "v_patch_policy_enforce": false,
      "audit_events_count": 0,
      "block_events_count": 0,
      "image_workload_info": null,
      "base_image_vulnerability": false,
      "base_image_name": ""
    },
    {
      "registry": "Host Images",
      "image_repository_name": "registry.aquasec.com/server",
      "image_name": "registry.aquasec.com/server:4.6",
      "image_digest": "sha256:0bdf4519c786be605d0d0bec65144d5ffc7074f958be7799a9ebb168b8a863a6",
      "referenced_vulnerabilities": null,
      "resource": {
        "type": "package",
        "format": "apk",
        "path": "",
        "name": "db",
        "version": "5.3.28-r1",
        "arch": "x86_64",
        "cpe": "pkg:/alpine:3.9.5:db:5.3.28-r1",
        "licenses": [
          "custom"
        ],
        "hash": ""
      },
      "name": "CVE-2017-3609",
      "description": "Vulnerability in the Data Store component of Oracle Berkeley DB. The supported version that is affected is Prior to 6.2.32. Difficult to exploit vulnerability allows unauthenticated attacker with logon to the infrastructure where Data Store executes to compromise Data Store. Successful attacks require human interaction from a person other than the attacker. Successful attacks of this vulnerability can result in takeover of Data Store. CVSS 3.0 Base Score 7.0 (Confidentiality, Integrity and Availability impacts). CVSS Vector: (CVSS:3.0/AV:L/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:H).",
      "publish_date": "2017-04-24",
      "modification_date": "2019-10-03",
      "vendor_severity": "low",
      "vendor_cvss2_score": 3.7,
      "vendor_cvss2_vectors": "AV:L/AC:H/Au:N/C:P/I:P/A:P",
      "vendor_statement": "",
      "vendor_url": "",
      "nvd_severity": "low",
      "nvd_cvss2_score": 3.7,
      "nvd_cvss2_vectors": "AV:L/AC:H/Au:N/C:P/I:P/A:P",
      "nvd_cvss3_severity": "high",
      "nvd_cvss3_score": 7,
      "nvd_cvss3_vectors": "CVSS:3.0/AV:L/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:H",
      "nvd_url": "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2017-3609",
      "fix_version": "",
      "solution": "",
      "classification": "",
      "qualys_ids": null,
      "aqua_score": 3.7,
      "aqua_severity": "low",
      "aqua_vectors": "AV:L/AC:H/Au:N/C:P/I:P/A:P",
      "aqua_scoring_system": "CVSS V2",
      "first_found_date": "2020-04-29",
      "last_found_date": "2020-04-29",
      "ancestor_pkg": "",
      "sibling_pkg": "",
      "v_patch_applied_by": "",
      "v_patch_applied_on": "",
      "v_patch_reverted_by": "",
      "v_patch_reverted_on": "",
      "v_patch_enforced_by": "",
      "v_patch_enforced_on": "",
      "v_patch_status": "no_patch",
      "acknowledged_date": "1970-01-01T00:00:00Z",
      "ack_scope": "",
      "ack_comment": "",
      "ack_author": "",
      "ack_expiration_days": 0,
      "ack_expiration_configured_at": "1970-01-01T00:00:00Z",
      "ack_expiration_configured_by": "",
      "v_patch_policy_name": "",
      "v_patch_policy_enforce": false,
      "audit_events_count": 0,
      "block_events_count": 0,
      "image_workload_info": null,
      "base_image_vulnerability": false,
      "base_image_name": ""
    },
    {
      "registry": "Host Images",
      "image_repository_name": "registry.aquasec.com/server",
      "image_name": "registry.aquasec.com/server:4.6",
      "image_digest": "sha256:0bdf4519c786be605d0d0bec65144d5ffc7074f958be7799a9ebb168b8a863a6",
      "referenced_vulnerabilities": null,
      "resource": {
        "type": "package",
        "format": "apk",
        "path": "",
        "name": "db",
        "version": "5.3.28-r1",
        "arch": "x86_64",
        "cpe": "pkg:/alpine:3.9.5:db:5.3.28-r1",
        "licenses": [
          "custom"
        ],
        "hash": ""
      },
      "name": "CVE-2017-3610",
      "description": "Vulnerability in the Data Store component of Oracle Berkeley DB. The supported version that is affected is Prior to 6.2.32. Difficult to exploit vulnerability allows unauthenticated attacker with logon to the infrastructure where Data Store executes to compromise Data Store. Successful attacks require human interaction from a person other than the attacker. Successful attacks of this vulnerability can result in takeover of Data Store. CVSS 3.0 Base Score 7.0 (Confidentiality, Integrity and Availability impacts). CVSS Vector: (CVSS:3.0/AV:L/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:H).",
      "publish_date": "2017-04-24",
      "modification_date": "2019-10-03",
      "vendor_severity": "low",
      "vendor_cvss2_score": 3.7,
      "vendor_cvss2_vectors": "AV:L/AC:H/Au:N/C:P/I:P/A:P",
      "vendor_statement": "",
      "vendor_url": "",
      "nvd_severity": "low",
      "nvd_cvss2_score": 3.7,
      "nvd_cvss2_vectors": "AV:L/AC:H/Au:N/C:P/I:P/A:P",
      "nvd_cvss3_severity": "high",
      "nvd_cvss3_score": 7,
      "nvd_cvss3_vectors": "CVSS:3.0/AV:L/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:H",
      "nvd_url": "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2017-3610",
      "fix_version": "",
      "solution": "",
      "classification": "",
      "qualys_ids": null,
      "aqua_score": 3.7,
      "aqua_severity": "low",
      "aqua_vectors": "AV:L/AC:H/Au:N/C:P/I:P/A:P",
      "aqua_scoring_system": "CVSS V2",
      "first_found_date": "2020-04-29",
      "last_found_date": "2020-04-29",
      "ancestor_pkg": "",
      "sibling_pkg": "",
      "v_patch_applied_by": "",
      "v_patch_applied_on": "",
      "v_patch_reverted_by": "",
      "v_patch_reverted_on": "",
      "v_patch_enforced_by": "",
      "v_patch_enforced_on": "",
      "v_patch_status": "no_patch",
      "acknowledged_date": "1970-01-01T00:00:00Z",
      "ack_scope": "",
      "ack_comment": "",
      "ack_author": "",
      "ack_expiration_days": 0,
      "ack_expiration_configured_at": "1970-01-01T00:00:00Z",
      "ack_expiration_configured_by": "",
      "v_patch_policy_name": "",
      "v_patch_policy_enforce": false,
      "audit_events_count": 0,
      "block_events_count": 0,
      "image_workload_info": null,
      "base_image_vulnerability": false,
      "base_image_name": ""
    },
    {
      "registry": "Host Images",
      "image_repository_name": "registry.aquasec.com/server",
      "image_name": "registry.aquasec.com/server:4.6",
      "image_digest": "sha256:0bdf4519c786be605d0d0bec65144d5ffc7074f958be7799a9ebb168b8a863a6",
      "referenced_vulnerabilities": null,
      "resource": {
        "type": "package",
        "format": "apk",
        "path": "",
        "name": "db",
        "version": "5.3.28-r1",
        "arch": "x86_64",
        "cpe": "pkg:/alpine:3.9.5:db:5.3.28-r1",
        "licenses": [
          "custom"
        ],
        "hash": ""
      },
      "name": "CVE-2017-3611",
      "description": "Vulnerability in the Data Store component of Oracle Berkeley DB. The supported version that is affected is Prior to 6.2.32. Difficult to exploit vulnerability allows unauthenticated attacker with logon to the infrastructure where Data Store executes to compromise Data Store. Successful attacks require human interaction from a person other than the attacker. Successful attacks of this vulnerability can result in takeover of Data Store. CVSS 3.0 Base Score 7.0 (Confidentiality, Integrity and Availability impacts). CVSS Vector: (CVSS:3.0/AV:L/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:H).",
      "publish_date": "2017-04-24",
      "modification_date": "2019-10-03",
      "vendor_severity": "low",
      "vendor_cvss2_score": 3.7,
      "vendor_cvss2_vectors": "AV:L/AC:H/Au:N/C:P/I:P/A:P",
      "vendor_statement": "",
      "vendor_url": "",
      "nvd_severity": "low",
      "nvd_cvss2_score": 3.7,
      "nvd_cvss2_vectors": "AV:L/AC:H/Au:N/C:P/I:P/A:P",
      "nvd_cvss3_severity": "high",
      "nvd_cvss3_score": 7,
      "nvd_cvss3_vectors": "CVSS:3.0/AV:L/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:H",
      "nvd_url": "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2017-3611",
      "fix_version": "",
      "solution": "",
      "classification": "",
      "qualys_ids": null,
      "aqua_score": 3.7,
      "aqua_severity": "low",
      "aqua_vectors": "AV:L/AC:H/Au:N/C:P/I:P/A:P",
      "aqua_scoring_system": "CVSS V2",
      "first_found_date": "2020-04-29",
      "last_found_date": "2020-04-29",
      "ancestor_pkg": "",
      "sibling_pkg": "",
      "v_patch_applied_by": "",
      "v_patch_applied_on": "",
      "v_patch_reverted_by": "",
      "v_patch_reverted_on": "",
      "v_patch_enforced_by": "",
      "v_patch_enforced_on": "",
      "v_patch_status": "no_patch",
      "acknowledged_date": "1970-01-01T00:00:00Z",
      "ack_scope": "",
      "ack_comment": "",
      "ack_author": "",
      "ack_expiration_days": 0,
      "ack_expiration_configured_at": "1970-01-01T00:00:00Z",
      "ack_expiration_configured_by": "",
      "v_patch_policy_name": "",
      "v_patch_policy_enforce": false,
      "audit_events_count": 0,
      "block_events_count": 0,
      "image_workload_info": null,
      "base_image_vulnerability": false,
      "base_image_name": ""
    },
    {
      "registry": "Host Images",
      "image_repository_name": "registry.aquasec.com/server",
      "image_name": "registry.aquasec.com/server:4.6",
      "image_digest": "sha256:0bdf4519c786be605d0d0bec65144d5ffc7074f958be7799a9ebb168b8a863a6",
      "referenced_vulnerabilities": null,
      "resource": {
        "type": "package",
        "format": "apk",
        "path": "",
        "name": "db",
        "version": "5.3.28-r1",
        "arch": "x86_64",
        "cpe": "pkg:/alpine:3.9.5:db:5.3.28-r1",
        "licenses": [
          "custom"
        ],
        "hash": ""
      },
      "name": "CVE-2017-3612",
      "description": "Vulnerability in the Data Store component of Oracle Berkeley DB. The supported version that is affected is Prior to 6.2.32. Difficult to exploit vulnerability allows unauthenticated attacker with logon to the infrastructure where Data Store executes to compromise Data Store. Successful attacks require human interaction from a person other than the attacker. Successful attacks of this vulnerability can result in takeover of Data Store. CVSS 3.0 Base Score 7.0 (Confidentiality, Integrity and Availability impacts). CVSS Vector: (CVSS:3.0/AV:L/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:H).",
      "publish_date": "2017-04-24",
      "modification_date": "2019-10-03",
      "vendor_severity": "low",
      "vendor_cvss2_score": 3.7,
      "vendor_cvss2_vectors": "AV:L/AC:H/Au:N/C:P/I:P/A:P",
      "vendor_statement": "",
      "vendor_url": "",
      "nvd_severity": "low",
      "nvd_cvss2_score": 3.7,
      "nvd_cvss2_vectors": "AV:L/AC:H/Au:N/C:P/I:P/A:P",
      "nvd_cvss3_severity": "high",
      "nvd_cvss3_score": 7,
      "nvd_cvss3_vectors": "CVSS:3.0/AV:L/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:H",
      "nvd_url": "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2017-3612",
      "fix_version": "",
      "solution": "",
      "classification": "",
      "qualys_ids": null,
      "aqua_score": 3.7,
      "aqua_severity": "low",
      "aqua_vectors": "AV:L/AC:H/Au:N/C:P/I:P/A:P",
      "aqua_scoring_system": "CVSS V2",
      "first_found_date": "2020-04-29",
      "last_found_date": "2020-04-29",
      "ancestor_pkg": "",
      "sibling_pkg": "",
      "v_patch_applied_by": "",
      "v_patch_applied_on": "",
      "v_patch_reverted_by": "",
      "v_patch_reverted_on": "",
      "v_patch_enforced_by": "",
      "v_patch_enforced_on": "",
      "v_patch_status": "no_patch",
      "acknowledged_date": "1970-01-01T00:00:00Z",
      "ack_scope": "",
      "ack_comment": "",
      "ack_author": "",
      "ack_expiration_days": 0,
      "ack_expiration_configured_at": "1970-01-01T00:00:00Z",
      "ack_expiration_configured_by": "",
      "v_patch_policy_name": "",
      "v_patch_policy_enforce": false,
      "audit_events_count": 0,
      "block_events_count": 0,
      "image_workload_info": null,
      "base_image_vulnerability": false,
      "base_image_name": ""
    }
  ]
}
